"""Ω-VLA-T∞³ R0.3-OMEGA — VLA-IR and Operator Universe wave 1."""

from .compilers import (
    Backend,
    CompilationArtifact,
    CompilerRegistry,
    compile_graphml,
    compile_latex,
    compile_lean4,
    compile_numpy,
    compile_rust_nalgebra,
    default_registry,
)
from .evaluator import EvaluationLimits, EvaluationReport, evaluate_operator
from .fixtures import finite_operator_fixture, typed_equation_program
from .identities import (
    Counterexample,
    IdentityCandidate,
    IdentityFactory,
    IdentityStatus,
    IdentityTrialReport,
    minimize_matrix_counterexample,
    run_identity_trials,
)
from .ir import (
    EdgeKind,
    IREdge,
    IRError,
    IRNode,
    IRValidationIssue,
    IRValidationReport,
    NodeKind,
    Provenance,
    VLAProgram,
    merge_programs,
)
from .oak import OAKGate, R03OAKReport, audit_operator_expression, audit_program
from .operators import (
    OperatorError,
    OperatorExpr,
    OperatorKind,
    OperatorProperty,
    operator_expression_from_dict,
)
from .types import (
    Dimension,
    MathType,
    Regularity,
    ScalarSystem,
    Shape,
    StructureKind,
    TypeSystemError,
    UncertaintySpec,
    UnitDimension,
    Variance,
    common_scalar_system,
    math_type_from_dict,
)

__all__ = [
    "Backend",
    "CompilationArtifact",
    "CompilerRegistry",
    "Counterexample",
    "Dimension",
    "EdgeKind",
    "EvaluationLimits",
    "EvaluationReport",
    "IREdge",
    "IRError",
    "IRNode",
    "IRValidationIssue",
    "IRValidationReport",
    "IdentityCandidate",
    "IdentityFactory",
    "IdentityStatus",
    "IdentityTrialReport",
    "MathType",
    "NodeKind",
    "OAKGate",
    "OperatorError",
    "OperatorExpr",
    "OperatorKind",
    "OperatorProperty",
    "Provenance",
    "R03OAKReport",
    "Regularity",
    "ScalarSystem",
    "Shape",
    "StructureKind",
    "TypeSystemError",
    "UncertaintySpec",
    "UnitDimension",
    "VLAProgram",
    "Variance",
    "audit_operator_expression",
    "audit_program",
    "common_scalar_system",
    "compile_graphml",
    "compile_latex",
    "compile_lean4",
    "compile_numpy",
    "compile_rust_nalgebra",
    "default_registry",
    "evaluate_operator",
    "finite_operator_fixture",
    "math_type_from_dict",
    "merge_programs",
    "minimize_matrix_counterexample",
    "operator_expression_from_dict",
    "run_identity_trials",
    "typed_equation_program",
]

__version__ = "0.3.0"
