"""Pure-text compilation backends for VLA-IR and OperatorExpr.

Backends emit deterministic source or interchange text.  Compilation here does
not execute external compilers and does not certify generated source.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from html import escape
import json
from typing import Any, Callable, Mapping

from .ir import EdgeKind, VLAProgram
from .operators import OperatorExpr, OperatorKind


class CompilerError(ValueError):
    pass


class Backend(str, Enum):
    NUMPY = "numpy"
    LATEX = "latex"
    GRAPHML = "graphml"
    LEAN4 = "lean4"
    RUST_NALgebra = "rust-nalgebra"
    JSON = "json"


@dataclass(frozen=True)
class CompilationArtifact:
    backend: Backend
    content: str
    source_digest: str
    complete: bool
    executable: bool
    warnings: tuple[str, ...] = ()
    theorem_claimed: bool = False
    formal_proof_claimed: bool = False
    scientific_validation_claimed: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "backend": self.backend.value,
            "content": self.content,
            "source_digest": self.source_digest,
            "complete": self.complete,
            "executable": self.executable,
            "warnings": list(self.warnings),
            "theorem_claimed": False,
            "formal_proof_claimed": False,
            "scientific_validation_claimed": False,
        }


class CompilerRegistry:
    def __init__(self) -> None:
        self._compilers: dict[Backend, Callable[[OperatorExpr], CompilationArtifact]] = {}

    def register(
        self,
        backend: Backend,
        compiler: Callable[[OperatorExpr], CompilationArtifact],
        *,
        replace: bool = False,
    ) -> None:
        if backend in self._compilers and not replace:
            raise CompilerError(f"backend already registered: {backend.value}")
        self._compilers[backend] = compiler

    def compile(self, expression: OperatorExpr, backend: Backend) -> CompilationArtifact:
        try:
            compiler = self._compilers[backend]
        except KeyError as exc:
            raise CompilerError(f"unregistered backend: {backend.value}") from exc
        expression.infer_type()
        return compiler(expression)

    def backends(self) -> tuple[str, ...]:
        return tuple(sorted(value.value for value in self._compilers))


def default_registry() -> CompilerRegistry:
    registry = CompilerRegistry()
    registry.register(Backend.NUMPY, compile_numpy)
    registry.register(Backend.LATEX, compile_latex)
    registry.register(Backend.LEAN4, compile_lean4)
    registry.register(Backend.RUST_NALgebra, compile_rust_nalgebra)
    registry.register(Backend.JSON, compile_operator_json)
    return registry


def compile_operator_json(expression: OperatorExpr) -> CompilationArtifact:
    return CompilationArtifact(
        backend=Backend.JSON,
        content=json.dumps(expression.to_dict(), ensure_ascii=False, sort_keys=True, indent=2) + "\n",
        source_digest=expression.digest(),
        complete=True,
        executable=False,
    )


def compile_numpy(expression: OperatorExpr) -> CompilationArtifact:
    symbols = expression.symbols()
    lines = [
        '"""Generated by Ω-VLA-T∞³ R0.3-OMEGA.',
        "",
        "Review generated source and validate its assumptions before use.",
        '"""',
        "from __future__ import annotations",
        "",
        "import numpy as np",
        "",
        "",
        "def evaluate(environment: dict[str, np.ndarray]) -> np.ndarray:",
    ]
    for symbol in symbols:
        lines.append(f"    {symbol} = np.asarray(environment[{symbol!r}], dtype=np.complex128)")
    lines.append(f"    return {_numpy_expr(expression)}")
    lines.append("")
    lines.append(f"EXPRESSION_DIGEST = {expression.digest()!r}")
    lines.append("THEOREM_CLAIMED = False")
    lines.append("SCIENTIFIC_VALIDATION_CLAIMED = False")
    return CompilationArtifact(
        backend=Backend.NUMPY,
        content="\n".join(lines) + "\n",
        source_digest=expression.digest(),
        complete=_numpy_supported(expression),
        executable=_numpy_supported(expression),
        warnings=() if _numpy_supported(expression) else ("one or more nodes require a dedicated backend",),
    )


def _numpy_supported(expression: OperatorExpr) -> bool:
    supported = {
        OperatorKind.SYMBOL,
        OperatorKind.IDENTITY,
        OperatorKind.ZERO,
        OperatorKind.MATRIX_LITERAL,
        OperatorKind.SUM,
        OperatorKind.DIFFERENCE,
        OperatorKind.COMPOSE,
        OperatorKind.SCALAR_MULTIPLY,
        OperatorKind.ADJOINT,
        OperatorKind.TRANSPOSE,
        OperatorKind.CONJUGATE,
        OperatorKind.INVERSE,
        OperatorKind.PSEUDOINVERSE,
        OperatorKind.POWER,
        OperatorKind.COMMUTATOR,
        OperatorKind.ANTICOMMUTATOR,
        OperatorKind.TENSOR_PRODUCT,
        OperatorKind.DIRECT_SUM,
        OperatorKind.KRONECKER_SUM,
        OperatorKind.LOW_RANK_UPDATE,
    }
    return expression.kind in supported and all(_numpy_supported(value) for value in expression.operands)


def _numpy_expr(expression: OperatorExpr) -> str:
    kind = expression.kind
    if kind == OperatorKind.SYMBOL:
        return expression.name
    if kind == OperatorKind.IDENTITY:
        size = expression.infer_type().shape.matrix_codomain().value
        return f"np.eye({size}, dtype=np.complex128)"
    if kind == OperatorKind.ZERO:
        rows, columns = expression.infer_type().shape.to_dict()
        return f"np.zeros(({rows}, {columns}), dtype=np.complex128)"
    if kind == OperatorKind.MATRIX_LITERAL:
        return f"np.asarray({expression.matrix_value!r}, dtype=np.complex128)"
    children = [_numpy_expr(value) for value in expression.operands]
    if kind == OperatorKind.SUM:
        return "(" + " + ".join(children) + ")"
    if kind == OperatorKind.DIFFERENCE:
        return f"({children[0]} - {children[1]})"
    if kind == OperatorKind.COMPOSE:
        return "(" + " @ ".join(children) + ")"
    if kind == OperatorKind.SCALAR_MULTIPLY:
        return f"({expression.scalar_value!r} * {children[0]})"
    if kind == OperatorKind.ADJOINT:
        return f"({children[0]}).conj().T"
    if kind == OperatorKind.TRANSPOSE:
        return f"({children[0]}).T"
    if kind == OperatorKind.CONJUGATE:
        return f"np.conjugate({children[0]})"
    if kind == OperatorKind.INVERSE:
        return f"np.linalg.inv({children[0]})"
    if kind == OperatorKind.PSEUDOINVERSE:
        return f"np.linalg.pinv({children[0]})"
    if kind == OperatorKind.POWER:
        return f"np.linalg.matrix_power({children[0]}, {expression.exponent})"
    if kind == OperatorKind.COMMUTATOR:
        return f"(({children[0]} @ {children[1]}) - ({children[1]} @ {children[0]}))"
    if kind == OperatorKind.ANTICOMMUTATOR:
        return f"(({children[0]} @ {children[1]}) + ({children[1]} @ {children[0]}))"
    if kind == OperatorKind.TENSOR_PRODUCT:
        result = children[0]
        for child in children[1:]:
            result = f"np.kron({result}, {child})"
        return result
    if kind == OperatorKind.DIRECT_SUM:
        shapes = [value.infer_type().shape.to_dict() for value in expression.operands]
        total_rows = sum(int(shape[0]) for shape in shapes)
        total_columns = sum(int(shape[1]) for shape in shapes)
        assignments: list[str] = []
        row = 0
        column = 0
        for child, shape in zip(children, shapes):
            rows, columns = map(int, shape)
            assignments.append(
                f"_out[{row}:{row + rows}, {column}:{column + columns}] = {child}"
            )
            row += rows
            column += columns
        # Expression contexts cannot contain statements; emit a lambda helper.
        body = "; ".join(assignments)
        return (
            "(lambda _out: (exec(" + repr(body) + ", {'_out': _out, 'np': np}), _out)[1])"
            f"(np.zeros(({total_rows}, {total_columns}), dtype=np.complex128))"
        )
    if kind == OperatorKind.KRONECKER_SUM:
        left_size = expression.operands[0].infer_type().shape.matrix_codomain().value
        right_size = expression.operands[1].infer_type().shape.matrix_codomain().value
        return (
            f"(np.kron({children[0]}, np.eye({right_size})) + "
            f"np.kron(np.eye({left_size}), {children[1]}))"
        )
    if kind == OperatorKind.LOW_RANK_UPDATE:
        return f"({children[0]} + {children[1]})"
    return f"NotImplementedError({kind.value!r})"


def compile_latex(expression: OperatorExpr) -> CompilationArtifact:
    content = _latex_expr(expression) + "\n"
    return CompilationArtifact(
        backend=Backend.LATEX,
        content=content,
        source_digest=expression.digest(),
        complete=True,
        executable=False,
    )


def _latex_expr(expression: OperatorExpr) -> str:
    kind = expression.kind
    if kind == OperatorKind.SYMBOL:
        return expression.name
    if kind == OperatorKind.IDENTITY:
        return r"I"
    if kind == OperatorKind.ZERO:
        return r"0"
    if kind == OperatorKind.MATRIX_LITERAL:
        rows = [" & ".join(_latex_scalar(value) for value in row) for row in expression.matrix_value]
        return r"\begin{bmatrix}" + r" \\ ".join(rows) + r"\end{bmatrix}"
    children = [_latex_expr(value) for value in expression.operands]
    if kind == OperatorKind.SUM:
        return " + ".join(children)
    if kind == OperatorKind.DIFFERENCE:
        return f"{children[0]} - {children[1]}"
    if kind == OperatorKind.COMPOSE:
        return r" \circ ".join(children)
    if kind == OperatorKind.SCALAR_MULTIPLY:
        return f"{_latex_scalar(expression.scalar_value)}\\,{children[0]}"
    if kind == OperatorKind.ADJOINT:
        return f"\\left({children[0]}\\right)^{{\\ast}}"
    if kind == OperatorKind.TRANSPOSE:
        return f"\\left({children[0]}\\right)^{{\\mathsf{{T}}}}"
    if kind == OperatorKind.CONJUGATE:
        return f"\\overline{{{children[0]}}}"
    if kind == OperatorKind.INVERSE:
        return f"\\left({children[0]}\\right)^{{-1}}"
    if kind == OperatorKind.PSEUDOINVERSE:
        return f"\\left({children[0]}\\right)^{{+}}"
    if kind == OperatorKind.POWER:
        return f"\\left({children[0]}\\right)^{{{expression.exponent}}}"
    if kind == OperatorKind.EXPONENTIAL:
        return f"\\exp\\left({children[0]}\\right)"
    if kind == OperatorKind.LOGARITHM:
        return f"\\log\\left({children[0]}\\right)"
    if kind == OperatorKind.COMMUTATOR:
        return f"\\left[{children[0]},{children[1]}\\right]"
    if kind == OperatorKind.ANTICOMMUTATOR:
        return f"\\left\\{{{children[0]},{children[1]}\\right\\}}"
    if kind == OperatorKind.TENSOR_PRODUCT:
        return r" \otimes ".join(children)
    if kind == OperatorKind.DIRECT_SUM:
        return r" \oplus ".join(children)
    if kind == OperatorKind.KRONECKER_SUM:
        return f"{children[0]}\\boxplus {children[1]}"
    if kind == OperatorKind.LOW_RANK_UPDATE:
        return f"{children[0]} + {children[1]}"
    return f"\\operatorname{{{kind.value}}}\\left(" + ",".join(children) + "\\right)"


def _latex_scalar(value: Any) -> str:
    if isinstance(value, complex):
        if value.imag == 0:
            return str(value.real)
        return f"({value.real}+{value.imag}i)"
    return str(value)


def compile_lean4(expression: OperatorExpr) -> CompilationArtifact:
    """Emit a traceable, explicit-incomplete Lean target.

    The target preserves the expression as data.  It does not pretend to encode
    all analytic side conditions required for a real theorem.
    """

    json_payload = json.dumps(expression.to_dict(), ensure_ascii=False, sort_keys=True)
    escaped = json_payload.replace("\\", "\\\\").replace('"', '\\"')
    content = f'''/- Generated by Ω-VLA-T∞³ R0.3-OMEGA.
   FORMALIZED_INCOMPLETE: this file is a proof target, not a proof. -/

namespace OmegaVLA

def expressionDigest : String := "{expression.digest()}"
def serializedExpression : String := "{escaped}"

def theoremClaimed : Bool := false
def formallyVerified : Bool := false

-- Replace this placeholder with a faithful typed formalization and proof.
theorem generated_target : True := by
  trivial

end OmegaVLA
'''
    return CompilationArtifact(
        backend=Backend.LEAN4,
        content=content,
        source_digest=expression.digest(),
        complete=False,
        executable=False,
        warnings=(
            "Lean output serializes the target and proves only True; no operator theorem is claimed",
        ),
    )


def compile_rust_nalgebra(expression: OperatorExpr) -> CompilationArtifact:
    symbols = expression.symbols()
    unsupported = not _rust_supported(expression)
    parameters = ", ".join(
        f"{name}: &DMatrix<Complex64>" for name in symbols
    )
    content = f'''// Generated by Ω-VLA-T∞³ R0.3-OMEGA.
// Review dimensions and numerical assumptions before production use.
use nalgebra::DMatrix;
use num_complex::Complex64;

pub const EXPRESSION_DIGEST: &str = "{expression.digest()}";
pub const THEOREM_CLAIMED: bool = false;
pub const SCIENTIFIC_VALIDATION_CLAIMED: bool = false;

pub fn evaluate({parameters}) -> DMatrix<Complex64> {{
    {_rust_expr(expression)}
}}
'''
    return CompilationArtifact(
        backend=Backend.RUST_NALgebra,
        content=content,
        source_digest=expression.digest(),
        complete=not unsupported,
        executable=not unsupported,
        warnings=() if not unsupported else ("Rust backend supports a bounded operator subset",),
    )


def _rust_supported(expression: OperatorExpr) -> bool:
    supported = {
        OperatorKind.SYMBOL,
        OperatorKind.MATRIX_LITERAL,
        OperatorKind.SUM,
        OperatorKind.DIFFERENCE,
        OperatorKind.COMPOSE,
        OperatorKind.SCALAR_MULTIPLY,
        OperatorKind.ADJOINT,
        OperatorKind.TRANSPOSE,
        OperatorKind.COMMUTATOR,
        OperatorKind.ANTICOMMUTATOR,
    }
    return expression.kind in supported and all(_rust_supported(value) for value in expression.operands)


def _rust_expr(expression: OperatorExpr) -> str:
    kind = expression.kind
    if kind == OperatorKind.SYMBOL:
        return f"{expression.name}.clone()"
    if kind == OperatorKind.MATRIX_LITERAL:
        rows, columns = expression.infer_type().shape.to_dict()
        values = []
        for row in expression.matrix_value:
            for value in row:
                number = complex(value)
                values.append(f"Complex64::new({number.real}, {number.imag})")
        return f"DMatrix::from_row_slice({rows}, {columns}, &[{', '.join(values)}])"
    children = [_rust_expr(value) for value in expression.operands]
    if kind == OperatorKind.SUM:
        return " + ".join(f"({child})" for child in children)
    if kind == OperatorKind.DIFFERENCE:
        return f"({children[0]}) - ({children[1]})"
    if kind == OperatorKind.COMPOSE:
        return " * ".join(f"({child})" for child in children)
    if kind == OperatorKind.SCALAR_MULTIPLY:
        number = complex(expression.scalar_value)
        return f"Complex64::new({number.real}, {number.imag}) * ({children[0]})"
    if kind == OperatorKind.ADJOINT:
        return f"({children[0]}).adjoint()"
    if kind == OperatorKind.TRANSPOSE:
        return f"({children[0]}).transpose()"
    if kind == OperatorKind.COMMUTATOR:
        return f"(({children[0]}) * ({children[1]})) - (({children[1]}) * ({children[0]}))"
    if kind == OperatorKind.ANTICOMMUTATOR:
        return f"(({children[0]}) * ({children[1]})) + (({children[1]}) * ({children[0]}))"
    return 'panic!("unsupported generated operator")'


def compile_graphml(program: VLAProgram) -> CompilationArtifact:
    validation = program.validate()
    warnings = tuple(issue.message for issue in validation.issues if issue.severity != "error")
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<graphml xmlns="http://graphml.graphdrawing.org/xmlns">',
        '  <key id="kind" for="all" attr.name="kind" attr.type="string"/>',
        '  <key id="label" for="node" attr.name="label" attr.type="string"/>',
        f'  <graph id="{escape(program.program_id)}" edgedefault="directed">',
    ]
    for node_id in sorted(program.nodes):
        node = program.nodes[node_id]
        lines.extend(
            [
                f'    <node id="{escape(node.node_id)}">',
                f'      <data key="kind">{escape(node.kind.value)}</data>',
                f'      <data key="label">{escape(node.label)}</data>',
                "    </node>",
            ]
        )
    for edge in sorted(program.edges, key=lambda value: value.stable_id()):
        lines.extend(
            [
                f'    <edge id="{escape(edge.stable_id())}" source="{escape(edge.source)}" target="{escape(edge.target)}">',
                f'      <data key="kind">{escape(edge.kind.value)}</data>',
                "    </edge>",
            ]
        )
    lines.extend(["  </graph>", "</graphml>", ""])
    return CompilationArtifact(
        backend=Backend.GRAPHML,
        content="\n".join(lines),
        source_digest=program.digest(),
        complete=validation.passed,
        executable=False,
        warnings=warnings,
    )
