"""Generated seed shard; observations remain reviewable."""
from __future__ import annotations
from .core import Relation
from .seed import action, dims, ev, p, sigs

def items(main: str, ttm: str, tfug: str):
    return (
        p("polyglot", "Ω-POLYGLOT-MULTIVERSE-T", "infrastructure", main, "PR#315", "Contextual Python/C/C++/Rust benchmark and autotuning laboratory.", dimensions=dims(truth=3, code=5, tests=4, baseline=5, reproducibility=3, integration=2, maintainability=3, external_validation=1, utility=4, falsifiability=5), signals=sigs(cli_available=True, schema_available=True, deterministic=True, m_minus_available=True), evidence=(ev("pr", "TFUGA-AI7-TRISTAN2#315"), ev("benchmark", "530 local candidates", "REPRODUCED")), status="benchmarked", claim="Local benchmark winners are context-specific, not universal language rankings.", risks=("hardware dependence", "benchmark overfitting"), next_action=action("Run calibrated ARM and x86 CI benchmarks", "benchmark", 20, "cross-machine champion stability report"), tags=("performance", "languages")),
        p("sequence-forms", "Ω-SUITE-FORM-T", "mathematics", main, "PR#314", "Exact finite-prefix sequence-form discovery and recurrence compilation.", dimensions=dims(truth=3, code=4, tests=3, baseline=3, reproducibility=4, integration=2, maintainability=3, external_validation=0, utility=4, falsifiability=4), signals=sigs(cli_available=True, schema_available=True, deterministic=True), evidence=(ev("pr", "TFUGA-AI7-TRISTAN2#314"), ev("test", "exact rational fixtures", "OBSERVED")), status="tested", claim="Finite-prefix candidates are exact on declared observations; global identities remain unproved.", risks=("non-unique continuation",), next_action=action("Evaluate against OEIS-like held-out synthetic families", "benchmark", 12, "held-out recovery report"), tags=("sequences", "symbolic")),
        p("space-hg", "Ω-SPACE-HG-T", "science", main, "PR#334", "Mission, orbit, attitude, EPS, thermal, RF and data co-simulation laboratory.", dimensions=dims(truth=3, code=4, tests=3, baseline=3, reproducibility=4, integration=2, maintainability=3, external_validation=0, utility=5, falsifiability=4), signals=sigs(cli_available=True, schema_available=True, deterministic=True, m_minus_available=True), evidence=(ev("pr", "TFUGA-AI7-TRISTAN2#334"), ev("test", "28 focused tests", "OBSERVED")), status="tested", claim="Reduced mission fixtures are educational research software, not flight qualification.", risks=("model fidelity", "regulatory and hardware limits"), next_action=action("Cross-check one LEO fixture with GMAT or Orekit", "benchmark", 20, "independent orbital baseline residuals"), relations=(Relation("depends_on", "rigid-body"),), tags=("space", "simulation")),
        p("emr-source", "Ω-EMR-SOURCE-T", "science", main, "PR#327", "Inverse spectrum-to-emission-mechanism compiler with safety routing.", dimensions=dims(truth=3, code=3, tests=2, baseline=2, reproducibility=3, integration=1, maintainability=3, external_validation=0, utility=4, falsifiability=3, risk_control=5), signals=sigs(cli_available=True, schema_available=True, deterministic=True), evidence=(ev("pr", "TFUGA-AI7-TRISTAN2#327"), ev("artifact", "20-mechanism atlas", "OBSERVED")), status="tested", claim="Engineering routing heuristics do not certify efficiency or safety.", risks=("hazardous source classes", "heuristic ranking"), next_action=action("Validate visible/IR routes against manufacturer data", "science", 12, "measured specification comparison"), tags=("electromagnetism", "safety")),
        p("intent-everything", "Ω-INTENT-TO-EVERYTHING-T", "operations", main, "PR#338", "Intent compiler to contracts, DAGs, generators, scaffolds and dry-run GitHub plans.", dimensions=dims(truth=2, code=4, tests=3, baseline=1, reproducibility=4, integration=3, maintainability=3, external_validation=0, product=2, utility=5, falsifiability=3), signals=sigs(cli_available=True, schema_available=True, deterministic=True, m_minus_available=True), evidence=(ev("pr", "TFUGA-AI7-TRISTAN2#338"), ev("test", "6 focused tests", "REPRODUCED")), status="tested", claim="The compiler produces reviewable scaffolds, not automatically correct implementations.", risks=("scaffold inflation", "generated-code quality"), next_action=action("Complete one intention into a released micro-package", "integration", 20, "idea-to-release closure receipt"), relations=(Relation("complements", "problem-atlas"),), tags=("orchestration", "generation")),
        p("code-dojo", "Ω-CODE-DOJO-T", "product", main, "PR#309", "Synthetic algorithmic practice, M-minus learning and multi-judge policy layer.", dimensions=dims(truth=2, code=4, tests=4, baseline=3, reproducibility=4, integration=2, maintainability=3, external_validation=0, product=3, user=0, utility=4, falsifiability=4), signals=sigs(cli_available=True, schema_available=True, deterministic=True, m_minus_available=True), evidence=(ev("pr", "TFUGA-AI7-TRISTAN2#309"), ev("test", "51 cumulative focused tests", "OBSERVED")), status="benchmarked", claim="Synthetic shadow fixtures do not establish mastery or solve referenced external problems.", risks=("platform terms", "synthetic-to-real transfer"), next_action=action("Run a four-week personal learning trial", "user", 16, "pre/post blinded skill benchmark", True), tags=("education", "algorithms")),
    )
