"""Generated seed shard; observations remain reviewable."""
from __future__ import annotations
from .core import Relation
from .seed import action, dims, ev, p, sigs

def items(main: str, ttm: str, tfug: str):
    return (
        p("lordeconv", "Ω-LORDECONV-T", "science", ttm, "PR#667", "Adaptive spectral deconvolution and falsification laboratory.", dimensions=dims(truth=3, code=5, tests=5, baseline=5, reproducibility=5, integration=3, maintainability=4, external_validation=1, product=2, utility=5, falsifiability=5), signals=sigs(ci_green=True, cli_available=True, schema_available=True, deterministic=True, m_minus_available=True), evidence=(ev("pr", "TTM-TFUGA-AI7-TRISTAN2#667"), ev("test", "160 focused tests after corrections", "REPRODUCED"), ev("benchmark", "907,200-scenario lazy grid", "OBSERVED")), status="benchmarked", claim="Synthetic recovery establishes no chemical identity or measured Raman/FTIR validation.", risks=("synthetic-real gap", "model mismatch"), next_action=action("Freeze and run a licensed Raman benchmark", "science", 24, "preregistered real-data comparison"), tags=("spectroscopy", "deconvolution")),
        p("atlas-github", "Ω-ATLAS-GITHUB-T", "infrastructure", ttm, "commit:fb49a34", "Cross-repository object, symbol, maturity, evidence and drift atlas.", dimensions=dims(truth=3, code=5, tests=4, baseline=3, reproducibility=5, integration=5, maintainability=4, external_validation=1, utility=5, falsifiability=4), signals=sigs(ci_green=True, cli_available=True, schema_available=True, deterministic=True, m_minus_available=True, real_data=True), evidence=(ev("commit", "TTM-TFUGA-AI7-TRISTAN2@fb49a34", "REPRODUCED"), ev("ci", "exact-head repository courts", "REPRODUCED")), status="externally_observed", claim="Repository and AST signatures support navigation, not semantic equivalence or value certification.", risks=("duplicate false positives", "private-content boundaries"), next_action=action("Export a reviewed cross-repo capability manifest", "integration", 12, "manual precision/recall labels"), relations=(Relation("complements", "productivity-obs"),), tags=("atlas", "github")),
        p("photon-time", "Ω-PHOTON-TIME-T", "science", "Tristan-TM-Poly/PEFA-FractalEnergySystem", "PR#90", "Temporal photonics stack from reduced Floquet to causal Maxwell-Drude and primary-data intake.", dimensions=dims(truth=3, code=4, tests=4, baseline=4, reproducibility=4, integration=4, maintainability=4, external_validation=0, utility=4, falsifiability=5), signals=sigs(ci_green=True, cli_available=True, schema_available=True, deterministic=True, m_minus_available=True), evidence=(ev("commit", "PEFA-FractalEnergySystem@d5ee7db", "REPRODUCED"), ev("ci", "merged R0.1-R0.11 stack", "REPRODUCED")), status="benchmarked", claim="R0 software stack remains blocked from R1 without admissible primary data and independent reproduction.", risks=("primary-data absence", "physical-model scope"), next_action=action("Ingest one admissible primary temporal-photonics dataset", "science", 24, "quantitative residual and provenance packet"), tags=("photonics", "floquet")),
        p("tfacc", "TFACC / OAKShield Core", "theory", "Tristan-TM-Poly/TFACC", "commit:399bf8e", "Categorical fractal field-theory scaffold with OAK hardening doctrine.", dimensions=dims(truth=1, code=1, tests=0, baseline=0, reproducibility=1, integration=1, maintainability=2, external_validation=0, utility=2, falsifiability=1, risk_control=4), signals=sigs(), evidence=(ev("commit", "TFACC@399bf8e", "OBSERVED"),), status="structured", claim="Current artifact is documentation-first and does not establish theorems.", risks=("undefined formal objects", "no proof modules"), next_action=action("Formalize one definition-example-counterexample triangle", "science", 16, "checked theorem index entry"), tags=("category-theory", "fields")),
        p("portfolio-os", "Ω-PROTOTYPE-PORTFOLIO-T", "operations", main, "issue#341", "This deterministic portfolio registry, scoring, graph, planning and OAK layer.", dimensions=dims(truth=2, code=4, tests=4, baseline=3, reproducibility=5, integration=5, maintainability=4, external_validation=0, product=2, utility=5, falsifiability=5, risk_control=5), signals=sigs(cli_available=True, schema_available=True, deterministic=True, m_minus_available=True), evidence=(ev("issue", "TFUGA-AI7-TRISTAN2#341"), ev("test", "51 focused local tests", "REPRODUCED")), status="tested", claim="Portfolio scores are deterministic routing heuristics, not truth or financial valuations.", risks=("seed subjectivity", "stale observations"), next_action=action("Calibrate scores against three independent reviewers", "benchmark", 10, "inter-rater agreement and disagreement ledger"), relations=(Relation("depends_on", "atlas-github"), Relation("complements", "productivity-obs")), tags=("portfolio", "oak")),
    )
