"""Generated seed shard; observations remain reviewable."""
from __future__ import annotations
from .core import Relation
from .seed import action, dims, ev, p, sigs

def items(main: str, ttm: str, tfug: str):
    return (
        p("rigid-body", "Ω-RIGID-BODY-T", "science", main, "PR#320", "Exact and numerical triaxial rigid-body laboratory with invariant ledgers.", dimensions=dims(truth=4, code=5, tests=4, baseline=4, reproducibility=4, integration=4, maintainability=4, external_validation=1, utility=4, falsifiability=5), signals=sigs(ci_green=True, cli_available=True, schema_available=True, deterministic=True, m_minus_available=True), evidence=(ev("pr", "TFUGA-AI7-TRISTAN2#320"), ev("test", "12 focused tests", "REPRODUCED"), ev("benchmark", "analytic/numerical residual ledger", "REPRODUCED")), status="benchmarked", claim="Deterministic analytic and numerical fixtures pass declared tolerances.", risks=("no physical experiment", "no flight qualification"), next_action=action("Publish a five-minute reproducible demo and compare with SciPy", "benchmark", 8, "external baseline report"), tags=("physics", "mechanics")),
        p("vla-identity", "Ω-VLA-T Identity Factory", "mathematics", main, "PR#324", "Typed matrix identity generation, assumption mutation and bounded falsification.", dimensions=dims(truth=3, code=5, tests=4, baseline=3, reproducibility=5, integration=4, maintainability=4, external_validation=0, utility=4, falsifiability=5), signals=sigs(ci_green=True, cli_available=True, schema_available=True, deterministic=True, m_minus_available=True), evidence=(ev("pr", "TFUGA-AI7-TRISTAN2#324"), ev("test", "7 focused tests", "REPRODUCED"), ev("artifact", "Python and SMT targets", "OBSERVED")), status="benchmarked", claim="Finite fixtures and compilers are deterministic; no theorem is claimed.", risks=("finite tests do not prove identities",), next_action=action("Formalize one identity end-to-end in Lean", "science", 20, "kernel-checked theorem artifact"), tags=("linear-algebra", "formalization")),
        p("vla-counterexample", "Ω-VLA-T Counterexample Superfactory", "mathematics", main, "PR#332", "Adversarial matrix families, witness minimization and hypothesis-repair candidates.", dimensions=dims(truth=3, code=5, tests=4, baseline=4, reproducibility=5, integration=4, maintainability=4, external_validation=0, utility=5, falsifiability=5), signals=sigs(ci_green=True, cli_available=True, schema_available=True, deterministic=True, m_minus_available=True), evidence=(ev("pr", "TFUGA-AI7-TRISTAN2#332"), ev("test", "9 focused tests", "REPRODUCED"), ev("artifact", "SQLite M-minus registry", "OBSERVED")), status="benchmarked", claim="Bounded counterexample campaigns reproduce declared fixtures.", risks=("absence of witness is not proof", "repair proposals are not sufficient conditions"), next_action=action("Benchmark against Hypothesis and SMT solvers", "benchmark", 16, "comparative falsification matrix"), relations=(Relation("depends_on", "vla-identity"),), tags=("counterexample", "oak")),
        p("web-hg", "Ω-WEB-HG-T", "infrastructure", main, "PR#329", "Policy-gated metadata absorption, SQLite resume, sharding, Merkle receipts and provenance search.", dimensions=dims(truth=3, code=5, tests=4, baseline=3, reproducibility=5, integration=5, maintainability=4, external_validation=2, product=2, user=1, utility=5, falsifiability=4), signals=sigs(ci_green=True, cli_available=True, schema_available=True, deterministic=True, m_minus_available=True, real_data=True), evidence=(ev("pr", "TFUGA-AI7-TRISTAN2#329"), ev("test", "16 R0.4 tests", "REPRODUCED"), ev("data", "official metadata adapters", "OBSERVED")), status="externally_observed", claim="Metadata-only adapters and shard invariants are software-tested.", risks=("public access is not republication permission", "network policies can change"), next_action=action("Run a retained multi-day public-source campaign", "integration", 12, "replayable real-data evidence bundle"), tags=("web", "provenance")),
        p("histoscience", "Ω-HISTOSCI-HG-T", "infrastructure", main, "PR#326", "Typed historiographic hypergraph kernel with evidence and causal caution.", dimensions=dims(truth=2, code=4, tests=4, baseline=2, reproducibility=4, integration=3, maintainability=4, external_validation=0, utility=3, falsifiability=3), signals=sigs(ci_green=True, cli_available=True, schema_available=True, deterministic=True, m_minus_available=True), evidence=(ev("pr", "TFUGA-AI7-TRISTAN2#326"), ev("test", "20 focused tests", "REPRODUCED")), status="tested", claim="Software fixtures are deterministic; generated cells are not historical facts.", risks=("source completeness", "causal overinterpretation"), next_action=action("Attach primary sources to one bounded history slice", "science", 16, "source-reviewed claim graph"), relations=(Relation("complements", "web-hg"),), tags=("history", "hypergraph")),
        p("problem-atlas", "Ω-PROBLEM-ATLAS-T", "mathematics", main, "PR#340", "Open-problem identities, evidence graphs, certified runners, routing and publication gates.", dimensions=dims(truth=2, code=4, tests=4, baseline=3, reproducibility=5, integration=2, maintainability=3, external_validation=0, utility=5, falsifiability=5), signals=sigs(cli_available=True, schema_available=True, deterministic=True, m_minus_available=True), evidence=(ev("pr", "TFUGA-AI7-TRISTAN2#340"), ev("artifact", "stacked R0.4-R0.10 contracts", "OBSERVED")), status="tested", claim="Stacked software contracts are candidates pending exact-head integration.", risks=("stacked PR debt", "current-open status requires fresh sources"), next_action=action("Consolidate the stack into one current-main vertical", "integration", 24, "green exact-head consolidated PR"), relations=(Relation("depends_on", "web-hg"),), tags=("open-problems", "evidence")),
    )
