"""Generated seed shard; observations remain reviewable."""
from __future__ import annotations
from .core import Relation
from .seed import action, dims, ev, p, sigs

def items(main: str, ttm: str, tfug: str):
    return (
        p("open-problems", "Ω-OPEN-PROBLEMS-ATLAS-T", "mathematics", main, "PR#301", "Source-aware problem genome, method cards, proof obligations and SQLite frontier.", dimensions=dims(truth=2, code=4, tests=3, baseline=2, reproducibility=4, integration=1, maintainability=3, external_validation=0, utility=4, falsifiability=4), signals=sigs(cli_available=True, schema_available=True, deterministic=True, m_minus_available=True), evidence=(ev("pr", "TFUGA-AI7-TRISTAN2#301"),), status="tested", claim="Logical obligation cells are not mathematical advances.", risks=("source freshness", "frontier-size inflation"), next_action=action("Merge concepts into Problem Atlas and archive duplicates", "integration", 16, "deduplicated capability map"), relations=(Relation("overlaps", "problem-atlas"),), tags=("research", "portfolio")),
        p("github-dialogue", "Ω-GITHUB-DIALOGUE-T", "operations", tfug, "PR#373", "Exact-head observation, causal failure reports, patch tournaments, worktrees and rollback.", dimensions=dims(truth=3, code=5, tests=5, baseline=4, reproducibility=5, integration=4, maintainability=4, external_validation=2, product=3, user=1, utility=5, falsifiability=5, risk_control=5), signals=sigs(ci_green=True, cli_available=True, schema_available=True, deterministic=True, m_minus_available=True, real_data=True), evidence=(ev("pr", "Tristan_Tardif-Morency_TFUG#373"), ev("test", "causal/worktree courts", "REPRODUCED"), ev("integration", "exact-head GitHub adapter", "OBSERVED")), status="externally_observed", claim="Bounded local repair proposals remain human-reviewed; root cause is not automatically proven.", risks=("sandbox limitations", "provider quality"), next_action=action("Repair one real red PR under a preregistered protocol", "user", 12, "before/after exact-head repair receipt", True), tags=("github", "repair")),
        p("oakgate-auditor", "OAKGate Repository Auditor", "product", tfug, "PR#362", "Read-only repository audit for tests, workflows, secrets, provenance and reproducibility.", dimensions=dims(truth=3, code=5, tests=5, baseline=3, reproducibility=5, integration=4, maintainability=4, external_validation=2, product=4, user=1, revenue=0, utility=5, falsifiability=5, risk_control=5), signals=sigs(ci_green=True, cli_available=True, schema_available=True, deterministic=True, m_minus_available=True, real_data=True), evidence=(ev("pr", "Tristan_Tardif-Morency_TFUG#362"), ev("test", "91 adversarial tests on predecessor", "REPRODUCED"), ev("audit", "real self-audit", "OBSERVED")), status="externally_observed", claim="Read-only findings are bounded indicators, not security or legal certification.", risks=("false positives", "no independent audit"), next_action=action("Deliver one authorized external repository audit", "user", 10, "user feedback and finding acceptance rate", True), relations=(Relation("complements", "github-dialogue"),), tags=("audit", "startup")),
        p("productivity-obs", "Ω-PRODUCTIVITY-OBS-T", "operations", ttm, "PR#693", "Anti-inflation GitHub productivity and evidence observatory.", dimensions=dims(truth=2, code=5, tests=5, baseline=3, reproducibility=5, integration=3, maintainability=4, external_validation=0, product=2, utility=4, falsifiability=5), signals=sigs(cli_available=True, schema_available=True, deterministic=True, m_minus_available=True), evidence=(ev("pr", "TTM-TFUGA-AI7-TRISTAN2#693"), ev("test", "100 local tests", "REPRODUCED")), status="benchmarked", claim="Human-equivalent estimates are priors, not time sheets or human-value measures.", risks=("uncalibrated priors", "Goodhart effects"), next_action=action("Prospectively calibrate estimates for 30 days", "benchmark", 12, "forecast versus observed closure report"), tags=("measurement", "anti-inflation")),
        p("startup-foundry", "Ω-STARTUP-T Venture Foundry", "product", ttm, "PR#694", "Asset-to-venture pipeline, evidence stages, permissions, offers and economics.", dimensions=dims(truth=2, code=5, tests=5, baseline=3, reproducibility=5, integration=3, maintainability=4, external_validation=0, product=4, user=0, revenue=0, utility=5, falsifiability=5, risk_control=5), signals=sigs(ci_green=True, cli_available=True, schema_available=True, deterministic=True, m_minus_available=True), evidence=(ev("pr", "TTM-TFUGA-AI7-TRISTAN2#694"), ev("ci", "3786 passed on corrected parent", "REPRODUCED")), status="benchmarked", claim="Synthetic venture evidence does not establish market demand, payment or retention.", risks=("simulation-to-market gap",), next_action=action("Conduct five non-leading problem interviews", "market", 10, "interview transcripts and problem-frequency table", True), relations=(Relation("depends_on", "oakgate-auditor"),), tags=("startup", "evidence")),
        p("zero-series", "Ω-ZERO-SERIES-T", "mathematics", ttm, "PR#701", "Complex-zero research foundry using series, contours, Padé and divisor evidence.", dimensions=dims(truth=3, code=5, tests=5, baseline=4, reproducibility=5, integration=2, maintainability=4, external_validation=0, utility=5, falsifiability=5), signals=sigs(cli_available=True, schema_available=True, deterministic=True, m_minus_available=True), evidence=(ev("pr", "TTM-TFUGA-AI7-TRISTAN2#701"), ev("test", "130 focused tests", "REPRODUCED"), ev("benchmark", "100k deterministic tasks", "OBSERVED")), status="benchmarked", claim="Numerical enclosure candidates are not analytic theorems without directed rounding and proof.", risks=("non-rigorous disk arithmetic", "open-problem overinterpretation"), next_action=action("Add directed interval arithmetic to one polynomial family", "science", 20, "machine-checkable zero-count certificates"), tags=("complex-analysis", "zeros")),
    )
