"""Ω Value OS — proof-carrying regenerative monetization kernel."""

from .book0 import (
    EconomicBOOK0,
    RegenerationReceipt,
    ablate_book0,
    future_work_annihilation,
    regeneration_passes,
    regeneration_receipt,
)
from .constitution import GateResult, evaluate_hard_gates, is_sensitive_action
from .engine import (
    automation_score,
    decide_automation,
    meta_stop_rule,
    proof_of_better,
    value_objective,
)
from .entitlements import EntitlementEvent, EntitlementEventType, EntitlementLedger
from .experiments import (
    ExperimentCandidate,
    PriceMutation,
    TournamentResult,
    experiment_option_value,
    minimum_sufficient_experiment,
    pricing_tournament,
    standard_price_mutations,
)
from .media import (
    ChannelProfile,
    ContentAsset,
    ContentProjection,
    channel_score,
    compile_projections,
    route_channels,
)
from .meta import GeneratorGenome, MetaCandidate, mutate_generator, should_create_meta_layer
from .meta_economy import (
    EconomicGenome,
    MetaEconomicCandidate,
    RepresentationCandidate,
    compile_economic_genomes,
    meta_generation_allowed,
    mutate_economic_genome,
    no_action_genome,
    representation_tournament,
)
from .models import (
    AutomationCandidate,
    AutomationDecision,
    AutomationLevel,
    AuthorityEnvelope,
    ProofCarryingRevenueStream,
    ProofOfBetterReceipt,
    RegenerationLevel,
    RevenueMode,
    StrategyGenome,
    ValueGenome,
)
from .portfolio import RevenueStreamMetrics, platform_concentration, prune_candidates, revenue_mode_mix
from .world_model import EconomicState, Shock, ShockResult, apply_shock, shock_curriculum

__all__ = [
    "AutomationCandidate",
    "AutomationDecision",
    "AutomationLevel",
    "AuthorityEnvelope",
    "ChannelProfile",
    "ContentAsset",
    "ContentProjection",
    "EconomicBOOK0",
    "EconomicGenome",
    "EconomicState",
    "EntitlementEvent",
    "EntitlementEventType",
    "EntitlementLedger",
    "ExperimentCandidate",
    "GateResult",
    "GeneratorGenome",
    "MetaCandidate",
    "MetaEconomicCandidate",
    "PriceMutation",
    "ProofCarryingRevenueStream",
    "ProofOfBetterReceipt",
    "RegenerationLevel",
    "RegenerationReceipt",
    "RepresentationCandidate",
    "RevenueMode",
    "RevenueStreamMetrics",
    "Shock",
    "ShockResult",
    "StrategyGenome",
    "TournamentResult",
    "ValueGenome",
    "ablate_book0",
    "apply_shock",
    "automation_score",
    "channel_score",
    "compile_economic_genomes",
    "compile_projections",
    "decide_automation",
    "evaluate_hard_gates",
    "experiment_option_value",
    "future_work_annihilation",
    "is_sensitive_action",
    "meta_generation_allowed",
    "meta_stop_rule",
    "minimum_sufficient_experiment",
    "mutate_economic_genome",
    "mutate_generator",
    "no_action_genome",
    "platform_concentration",
    "pricing_tournament",
    "proof_of_better",
    "prune_candidates",
    "regeneration_passes",
    "regeneration_receipt",
    "representation_tournament",
    "revenue_mode_mix",
    "route_channels",
    "shock_curriculum",
    "should_create_meta_layer",
    "standard_price_mutations",
    "value_objective",
]
