import omega_naruto_hmagfm as naruto


def test_public_api_exports_r12_operational_surface() -> None:
    expected = {
        "AgentProposal",
        "ChakraBudget",
        "ClaimStatus",
        "GateDecision",
        "GatePolicy",
        "GateReport",
        "GenjutsuCode",
        "GenjutsuFinding",
        "StrategyBenchmark",
        "GraphEdge",
        "GraphNode",
        "HGFMGraph",
        "DecisionRobustness",
        "ProposalPerturbation",
        "RobustnessScenario",
        "ScenarioDecision",
        "CorpusAxes",
        "CorpusManifest",
        "CorpusRecord",
        "FrontierBudget",
        "FrontierCheckpoint",
        "FrontierValidationReport",
        "FrontierScaleIndex",
        "ScaleManifest",
        "ScalePartition",
        "ScalePlan",
        "ScaleShardReceipt",
        "ScaleValidationFinding",
        "ScaleValidationReport",
        "ParallelFinding",
        "ParallelScaleIndex",
        "ParallelValidationReport",
        "ShardIndexPartial",
        "ShardValidationProof",
        "FrontierRunEntry",
        "FrontierRunLedger",
        "LedgerFinding",
        "analyze_decision_robustness",
        "audit_proposal",
        "benchmark_strategies",
        "build_hgfmn_graph",
        "build_run_ledger",
        "build_scale_index",
        "build_scale_index_parallel",
        "decode_ordinal",
        "default_axes",
        "default_robustness_scenarios",
        "evaluate_publication",
        "has_blocking_finding",
        "highest_confidence",
        "iter_records",
        "majority_vote",
        "oak_merge",
        "plan_scale_run",
        "proposal_score",
        "record_from_ordinal",
        "to_claim_packet",
        "to_mminus_registry",
        "validate_frontier",
        "validate_scale_corpus",
        "validate_scale_corpus_parallel",
        "write_corpus",
        "write_parallel_index",
        "write_parallel_validation",
        "write_run_ledger",
        "write_scale_corpus",
        "write_scale_index",
    }
    assert expected.issubset(set(naruto.__all__))
    for name in expected:
        assert hasattr(naruto, name)
