from __future__ import annotations

import json
from pathlib import Path

import pytest

from omega_polyglot_bench_t.r02.campaign import materialize
from omega_polyglot_bench_t.r02.catalog import generate_catalog
from omega_polyglot_bench_t.r02.frontier import LogicalFrontier
from omega_polyglot_bench_t.r02.generator import generate_affine_source
from omega_polyglot_bench_t.r02.hardware import fingerprint
from omega_polyglot_bench_t.r02.ir import affine_vector_ir, derive_obligations
from omega_polyglot_bench_t.r02.memory import MemoryEvent, MemoryLedger
from omega_polyglot_bench_t.r02.model import ScoreVector
from omega_polyglot_bench_t.r02.selector import dominates, pareto_front, select_weighted
from omega_polyglot_bench_t.r02.seed import materialize_seed_atlas


def make_frontier(count: int = 1024) -> LogicalFrontier:
    return LogicalFrontier(tuple(spec.algorithm_id for spec in generate_catalog(count)))


def test_catalog_has_1024_unique_valid_specs() -> None:
    specs = generate_catalog(1024)
    assert len(specs) == 1024
    assert len({spec.algorithm_id for spec in specs}) == 1024
    assert len({spec.digest for spec in specs}) == 1024
    assert {spec.family for spec in specs} == {
        "vector", "matrix", "tensor", "signal", "wavelet", "statistics", "optimization", "graph",
        "hypergraph", "geometry", "compression", "coding", "symbolic", "physics", "parsing", "systems",
    }
    for spec in specs:
        spec.validate()
        assert spec.schema_version == "omega.algorithm-spec.v2"
        assert spec.contract.deterministic is True


def test_frontier_exceeds_two_billion_without_enumeration() -> None:
    frontier = make_frontier()
    assert frontier.axes.variants_per_algorithm == 2_621_440
    assert frontier.size == 2_684_354_560
    assert frontier.size > 2_000_000_000


def test_frontier_random_access_round_trip() -> None:
    frontier = make_frontier(32)
    indices = (0, 1, 7, 8, 127, 1_000_003, frontier.size - 1)
    for index in indices:
        address = frontier.address_at(index)
        assert frontier.index_of(address) == index
        assert address.variant_id.startswith("var_")
        assert address.uri.startswith("variant://")
    with pytest.raises(IndexError):
        frontier.address_at(frontier.size)


def test_sampling_is_deterministic_unique_and_bounded() -> None:
    frontier = make_frontier(8)
    first = frontier.sample_indices(10_000, seed=42)
    second = frontier.sample_indices(10_000, seed=42)
    assert first == second
    assert len(first) == len(set(first)) == 10_000
    assert min(first) >= 0 and max(first) < frontier.size


def test_ir_and_obligations_cover_risks() -> None:
    ir = affine_vector_ir()
    ir.validate()
    obligations = derive_obligations("simd-explicit", "f32", "strided", "threads-8")
    assert "vector-tail-correctness" in obligations
    assert "reduced-precision-error-budget" in obligations
    assert "layout-index-map-correctness" in obligations
    assert "race-freedom" in obligations


def test_generators_emit_four_distinct_languages() -> None:
    artifacts = {
        language: generate_affine_source(language, "simd-auto")
        for language in ("python", "c", "cpp", "rust")
    }
    assert len({artifact.sha256 for artifact in artifacts.values()}) == 4
    assert "def omega_vector_affine_f64" in artifacts["python"].content
    assert "#include <stddef.h>" in artifacts["c"].content
    assert 'extern "C"' in artifacts["cpp"].content
    assert "unsafe extern \"C\"" in artifacts["rust"].content
    assert all("Generated by" in artifact.content for artifact in artifacts.values())


def test_materialize_10000_records_sharded_and_resume_safe(tmp_path: Path) -> None:
    frontier = make_frontier(64)
    output = tmp_path / "campaign"
    manifest = materialize(frontier, output, count=10_000, shard_size=1024)
    assert manifest.requested_count == 10_000
    assert manifest.next_index == 10_000
    assert manifest.accepted + manifest.rejected == 10_000
    assert manifest.duplicate_ids == 0
    assert len(manifest.shards) == 10
    lines = sum(
        1 for path in (output / "shards").glob("*.jsonl")
        for line in path.read_text().splitlines() if line
    )
    assert lines == 10_000
    resumed = materialize(frontier, output, count=10_000, shard_size=1024, resume=True)
    assert resumed.to_dict() == manifest.to_dict()
    persisted = json.loads((output / "manifest.json").read_text())
    assert persisted["permanent_total_cap"] is None
    assert persisted["universal_language_winner_claimed"] is False
    assert persisted["scientific_validation_claimed"] is False


def test_multiobjective_pareto_and_selection_reject_incorrect() -> None:
    scores = (
        ScoreVector("python", True, 100, 10, 1000, 0, 0, 1.0, 0.95),
        ScoreVector("c", True, 30, 40, 800, 1e-14, 15, 0.9, 0.7),
        ScoreVector("rust", True, 35, 38, 700, 1e-14, 20, 0.85, 0.95),
        ScoreVector("bad-fast", False, 1, 1000, 1, 1.0, 1, 0.1, 0.1),
    )
    assert dominates(scores[1], scores[3])
    front = pareto_front(scores)
    assert {score.variant_id for score in front} == {"python", "c", "rust"}
    selected = select_weighted(scores)
    assert selected.correct
    assert selected.variant_id != "bad-fast"


def test_append_only_positive_negative_memory(tmp_path: Path) -> None:
    ledger = MemoryLedger(tmp_path / "memory.jsonl")
    plus = ledger.append(MemoryEvent("M+", "var_good", "latency-champion", {"median_ns": 10}))
    minus = ledger.append(MemoryEvent("M-", "var_bad", "numerical-divergence", {"max_abs_error": 0.5}))
    events = ledger.read()
    assert plus != minus
    assert [event["kind"] for event in events] == ["M+", "M-"]
    assert events[1]["code"] == "numerical-divergence"


def test_hardware_fingerprint_is_conservative_and_stable_shape() -> None:
    profile = fingerprint()
    payload = profile.to_dict()
    assert profile.profile_id.startswith("hw_")
    assert payload["cpu_count"] >= 1
    assert isinstance(payload["features"], list)


def test_seed_atlas_materializes_16384_compact_cells(tmp_path: Path) -> None:
    manifest = materialize_seed_atlas(tmp_path / "seed")
    assert manifest["records"] == 16_384
    assert len(manifest["shards"]) == 4
    observed = sum(
        1 for path in (tmp_path / "seed").glob("research-cells-*.jsonl")
        for line in path.read_text().splitlines() if line
    )
    assert observed == 16_384
    assert manifest["compiled_records"] == 0
    assert manifest["scientific_validation_claimed"] is False
