from __future__ import annotations

WORLDS_3 = ({'index': 48,
  'id': 'mof',
  'name': 'MOF',
  'domain': 'porous-crystal',
  'examples': ('cadre métallo-organique',),
  'required_checks': ('topology', 'guest', 'stability')},
 {'index': 49,
  'id': 'cof',
  'name': 'COF',
  'domain': 'porous-crystal',
  'examples': ('cadre organique covalent',),
  'required_checks': ('topology', 'porosity', 'synthesis')},
 {'index': 50,
  'id': 'zeolite',
  'name': 'Zéolithes et réseaux poreux cristallins',
  'domain': 'porous-crystal',
  'examples': ('tamis moléculaire',),
  'required_checks': ('framework', 'adsorption', 'exchange')},
 {'index': 51,
  'id': 'geological',
  'name': 'Matériaux géologiques',
  'domain': 'natural',
  'examples': ('minéral', 'roche'),
  'required_checks': ('heterogeneity', 'pressure', 'weathering')},
 {'index': 52,
  'id': 'ice-extreme-molecular',
  'name': 'Glaces et solides moléculaires extrêmes',
  'domain': 'extreme',
  'examples': ('glace', 'hydrate'),
  'required_checks': ('phase', 'pressure', 'proton order')},
 {'index': 53,
  'id': 'extreme-compression',
  'name': 'Solides sous compression extrême',
  'domain': 'extreme',
  'examples': ('phase dense', 'matériau superdur'),
  'required_checks': ('equation of state', 'metastability', 'decompression')},
 {'index': 54,
  'id': 'extreme-defect-flux',
  'name': 'Solides sous flux extrême de défauts',
  'domain': 'extreme',
  'examples': ('cascade de défauts',),
  'required_checks': ('exposure history', 'defect evolution', 'swelling')},
 {'index': 55,
  'id': 'extreme-containment',
  'name': 'Solides de confinement extrême',
  'domain': 'extreme',
  'examples': ('matrice de confinement', 'barrière durable'),
  'required_checks': ('long-term stability', 'chemistry', 'containment')},
 {'index': 56,
  'id': 'cryogenic-solid',
  'name': 'Solides cryogéniques',
  'domain': 'extreme',
  'examples': ('basse température',),
  'required_checks': ('transition', 'embrittlement', 'thermal contraction')},
 {'index': 57,
  'id': 'high-temperature-solid',
  'name': 'Solides à haute température',
  'domain': 'extreme',
  'examples': ('réfractaire', 'superalliage'),
  'required_checks': ('creep', 'oxidation', 'thermal gradients')},
 {'index': 58,
  'id': 'fractal-solid',
  'name': 'Solides fractals',
  'domain': 'tristan',
  'examples': ('porosité auto-similaire',),
  'required_checks': ('scale range', 'manufacturability', 'baseline')},
 {'index': 59,
  'id': 'perforated-fractal-hexagon',
  'name': 'Hexagones fractals troués',
  'domain': 'tristan',
  'examples': ('réseau hexagonal troué',),
  'required_checks': ('stress concentration', 'transport', 'fabrication')},
 {'index': 60,
  'id': 'fractal-crystal',
  'name': 'Cristaux fractals',
  'domain': 'tristan',
  'examples': ('ordre multi-échelle',),
  'required_checks': ('diffraction', 'hierarchy', 'artifact control')},
 {'index': 61,
  'id': 'mycelial-solid',
  'name': 'Solides mycéliens',
  'domain': 'tristan',
  'examples': ('réseau redondant',),
  'required_checks': ('connectivity', 'repair', 'transport')},
 {'index': 62,
  'id': 'computational-solid',
  'name': 'Solides computationnels',
  'domain': 'tristan',
  'examples': ('logique mécanique', 'mémoire matérielle'),
  'required_checks': ('function', 'energy', 'verification')},
 {'index': 63,
  'id': 'unknown-solid',
  'name': 'Solides inconnus',
  'domain': 'unknown',
  'examples': ('candidat non synthétisé',),
  'required_checks': ('quarantine', 'falsification', 'provenance')})
