from __future__ import annotations

WORLDS_2 = ({'index': 32,
  'id': 'battery-material',
  'name': 'Matériaux de batteries',
  'domain': 'electrochemical',
  'examples': ('cathode', 'anode', 'électrolyte'),
  'required_checks': ('redox', 'interfaces', 'cycling')},
 {'index': 33,
  'id': 'magnetic-material',
  'name': 'Matériaux magnétiques',
  'domain': 'magnetic',
  'examples': ('ferromagnétique', 'antiferromagnétique'),
  'required_checks': ('domains', 'anisotropy', 'hysteresis')},
 {'index': 34,
  'id': 'superconductor',
  'name': 'Supraconducteurs',
  'domain': 'quantum',
  'examples': ('conventionnel', 'cuprate'),
  'required_checks': ('critical temperature', 'field', 'current')},
 {'index': 35,
  'id': 'topological-material',
  'name': 'Matériaux topologiques',
  'domain': 'quantum',
  'examples': ('isolant topologique', 'semi-métal'),
  'required_checks': ('symmetry', 'invariant', 'surface states')},
 {'index': 36,
  'id': 'strongly-correlated',
  'name': 'Matériaux fortement corrélés',
  'domain': 'quantum',
  'examples': ('Mott', 'fermion lourd'),
  'required_checks': ('correlations', 'phase diagram', 'measurement')},
 {'index': 37,
  'id': 'photonic-material',
  'name': 'Matériaux photoniques',
  'domain': 'wave',
  'examples': ('cristal photonique', 'métasurface'),
  'required_checks': ('band structure', 'loss', 'fabrication')},
 {'index': 38,
  'id': 'phononic-material',
  'name': 'Matériaux phononiques',
  'domain': 'wave',
  'examples': ('cristal phononique', 'guide acoustique'),
  'required_checks': ('dispersion', 'damping', 'scale')},
 {'index': 39,
  'id': 'mechanical-metamaterial',
  'name': 'Métamatériaux mécaniques',
  'domain': 'architected',
  'examples': ('auxétique', 'treillis'),
  'required_checks': ('topology', 'buckling', 'manufacturing')},
 {'index': 40,
  'id': 'electromagnetic-metamaterial',
  'name': 'Métamatériaux électromagnétiques',
  'domain': 'architected',
  'examples': ('absorbeur', 'résonateur'),
  'required_checks': ('effective medium', 'loss', 'bandwidth')},
 {'index': 41,
  'id': 'thermoelectric',
  'name': 'Matériaux thermoélectriques',
  'domain': 'functional',
  'examples': ('tellurure', 'half-Heusler'),
  'required_checks': ('Seebeck', 'conductivity', 'stability')},
 {'index': 42,
  'id': 'phase-change',
  'name': 'Matériaux à changement de phase',
  'domain': 'functional',
  'examples': ('amorphe-cristal', 'transition structurale'),
  'required_checks': ('hysteresis', 'cycling', 'kinetics')},
 {'index': 43,
  'id': 'shape-memory',
  'name': 'Matériaux à mémoire de forme',
  'domain': 'functional',
  'examples': ('alliage', 'polymère'),
  'required_checks': ('transformation', 'fatigue', 'temperature')},
 {'index': 44,
  'id': 'self-healing',
  'name': 'Matériaux auto-réparants',
  'domain': 'functional',
  'examples': ('capsules', 'réseau vasculaire'),
  'required_checks': ('healing efficiency', 'repeatability', 'aging')},
 {'index': 45,
  'id': 'active-material',
  'name': 'Matériaux actifs',
  'domain': 'functional',
  'examples': ('électroactif', 'magnétoactif'),
  'required_checks': ('energy input', 'stability', 'control')},
 {'index': 46,
  'id': 'reconfigurable',
  'name': 'Matériaux reconfigurables',
  'domain': 'functional',
  'examples': ('multi-stable', 'rigidité ajustable'),
  'required_checks': ('state space', 'actuation', 'fatigue')},
 {'index': 47,
  'id': 'nonequilibrium-solid',
  'name': 'Matériaux hors équilibre',
  'domain': 'nonequilibrium',
  'examples': ('état entraîné', 'solide vieillissant'),
  'required_checks': ('drive', 'dissipation', 'timescale')})
