from __future__ import annotations

WORLDS_0 = ({'index': 0,
  'id': 'metal-pure',
  'name': 'Métaux purs',
  'domain': 'metallic',
  'examples': ('cristal métallique', 'nanocristal'),
  'required_checks': ('phase', 'texture', 'dislocations')},
 {'index': 1,
  'id': 'alloy-conventional',
  'name': 'Alliages conventionnels',
  'domain': 'metallic',
  'examples': ('acier', 'alliage aluminium'),
  'required_checks': ('phase', 'precipitation', 'fatigue')},
 {'index': 2,
  'id': 'alloy-high-entropy',
  'name': 'Alliages à haute entropie',
  'domain': 'metallic',
  'examples': ('solution multi-principale',),
  'required_checks': ('phase stability', 'chemical disorder', 'baseline')},
 {'index': 3,
  'id': 'intermetallic',
  'name': 'Intermétalliques',
  'domain': 'metallic',
  'examples': ('aluminure', 'phase de Laves'),
  'required_checks': ('ordering', 'brittleness', 'temperature')},
 {'index': 4,
  'id': 'ionic-crystal',
  'name': 'Cristaux ioniques',
  'domain': 'ceramic',
  'examples': ('halogénure', 'oxyde'),
  'required_checks': ('charge balance', 'defects', 'dielectric')},
 {'index': 5,
  'id': 'covalent-network',
  'name': 'Réseaux covalents',
  'domain': 'ceramic',
  'examples': ('diamant', 'carbure'),
  'required_checks': ('coordination', 'fracture', 'surface')},
 {'index': 6,
  'id': 'structural-ceramic',
  'name': 'Céramiques structurales',
  'domain': 'ceramic',
  'examples': ('alumine', 'zircone'),
  'required_checks': ('porosity', 'flaw statistics', 'toughness')},
 {'index': 7,
  'id': 'functional-ceramic',
  'name': 'Céramiques fonctionnelles',
  'domain': 'ceramic',
  'examples': ('piézoélectrique', 'ferroélectrique'),
  'required_checks': ('domains', 'hysteresis', 'coupling')},
 {'index': 8,
  'id': 'inorganic-glass',
  'name': 'Verres inorganiques',
  'domain': 'glass',
  'examples': ('silicate', 'chalcogénure'),
  'required_checks': ('fictive temperature', 'relaxation', 'surface flaws')},
 {'index': 9,
  'id': 'metallic-glass',
  'name': 'Verres métalliques',
  'domain': 'glass',
  'examples': ('ruban amorphe', 'verre massif'),
  'required_checks': ('amorphicity', 'shear bands', 'thermal history')},
 {'index': 10,
  'id': 'molecular-crystal',
  'name': 'Cristaux moléculaires',
  'domain': 'molecular',
  'examples': ('organique', 'liaison hydrogène'),
  'required_checks': ('polymorphs', 'packing', 'temperature')},
 {'index': 11,
  'id': 'thermoplastic',
  'name': 'Polymères thermoplastiques',
  'domain': 'polymer',
  'examples': ('amorphe', 'semi-cristallin'),
  'required_checks': ('molecular weight', 'crystallinity', 'rate dependence')},
 {'index': 12,
  'id': 'thermoset',
  'name': 'Polymères thermodurcissables',
  'domain': 'polymer',
  'examples': ('époxy', 'réseau réticulé'),
  'required_checks': ('crosslink density', 'cure', 'aging')},
 {'index': 13,
  'id': 'elastomer',
  'name': 'Élastomères',
  'domain': 'polymer',
  'examples': ('caoutchouc', 'silicone'),
  'required_checks': ('hyperelasticity', 'temperature', 'crosslinks')},
 {'index': 14,
  'id': 'conducting-polymer',
  'name': 'Polymères conducteurs',
  'domain': 'polymer',
  'examples': ('dopé', 'électroactif'),
  'required_checks': ('dopant', 'percolation', 'stability')},
 {'index': 15,
  'id': 'fiber-composite',
  'name': 'Composites fibreux',
  'domain': 'composite',
  'examples': ('stratifié', 'tissé'),
  'required_checks': ('anisotropy', 'interface', 'delamination')})
