from __future__ import annotations

WORLDS_1 = ({'index': 16,
  'id': 'particle-composite',
  'name': 'Composites particulaires',
  'domain': 'composite',
  'examples': ('dispersion', 'charge fonctionnelle'),
  'required_checks': ('distribution', 'interface', 'percolation')},
 {'index': 17,
  'id': 'nanocomposite',
  'name': 'Nanocomposites',
  'domain': 'composite',
  'examples': ('nanotube', 'graphène'),
  'required_checks': ('dispersion', 'agglomeration', 'interface')},
 {'index': 18,
  'id': 'multilayer',
  'name': 'Laminés et multicouches',
  'domain': 'interface',
  'examples': ('revêtement', 'superréseau'),
  'required_checks': ('adhesion', 'residual stress', 'diffusion')},
 {'index': 19,
  'id': 'porous-material',
  'name': 'Matériaux poreux',
  'domain': 'porous',
  'examples': ('porosité ouverte', 'hiérarchique'),
  'required_checks': ('connectivity', 'transport', 'strength')},
 {'index': 20,
  'id': 'foam',
  'name': 'Mousses',
  'domain': 'porous',
  'examples': ('métallique', 'polymérique'),
  'required_checks': ('relative density', 'cell topology', 'buckling')},
 {'index': 21,
  'id': 'aerogel',
  'name': 'Aérogels',
  'domain': 'porous',
  'examples': ('silice', 'carbone'),
  'required_checks': ('surface area', 'fragility', 'transport')},
 {'index': 22,
  'id': 'granular-solid',
  'name': 'Matériaux granulaires',
  'domain': 'granular',
  'examples': ('poudre', 'sol'),
  'required_checks': ('contact network', 'jamming', 'segregation')},
 {'index': 23,
  'id': 'soft-solid',
  'name': 'Solides mous',
  'domain': 'soft',
  'examples': ('gel', 'colloïde bloqué'),
  'required_checks': ('timescale', 'viscoelasticity', 'solvent')},
 {'index': 24,
  'id': 'biological-solid',
  'name': 'Solides biologiques',
  'domain': 'biological',
  'examples': ('os', 'bois', 'nacre'),
  'required_checks': ('hierarchy', 'hydration', 'remodeling')},
 {'index': 25,
  'id': 'synthetic-biomaterial',
  'name': 'Biomatériaux synthétiques',
  'domain': 'biological',
  'examples': ('implant', 'échafaudage'),
  'required_checks': ('biocompatibility', 'degradation', 'sterilization')},
 {'index': 26,
  'id': 'two-dimensional',
  'name': 'Matériaux bidimensionnels',
  'domain': 'low-dimensional',
  'examples': ('graphène', 'dichalcogénure'),
  'required_checks': ('substrate', 'edges', 'thickness')},
 {'index': 27,
  'id': 'one-dimensional',
  'name': 'Matériaux unidimensionnels',
  'domain': 'low-dimensional',
  'examples': ('nanofil', 'nanotube'),
  'required_checks': ('confinement', 'surface', 'contacts')},
 {'index': 28,
  'id': 'zero-dimensional-assembly',
  'name': 'Nanoamas et solides 0D assemblés',
  'domain': 'low-dimensional',
  'examples': ('point quantique', 'supercristal'),
  'required_checks': ('size distribution', 'ligands', 'packing')},
 {'index': 29,
  'id': 'semiconductor',
  'name': 'Semi-conducteurs',
  'domain': 'electronic',
  'examples': ('Si', 'III-V', 'oxyde'),
  'required_checks': ('band gap', 'dopants', 'traps')},
 {'index': 30,
  'id': 'dielectric',
  'name': 'Isolants et diélectriques',
  'domain': 'electronic',
  'examples': ('haute permittivité', 'faible perte'),
  'required_checks': ('breakdown', 'loss', 'interfaces')},
 {'index': 31,
  'id': 'ionic-conductor',
  'name': 'Conducteurs ioniques',
  'domain': 'electrochemical',
  'examples': ('électrolyte solide', 'protonique'),
  'required_checks': ('mobile species', 'barrier', 'grain boundaries')})
