"""Curated mechanism atlas for electromagnetic-source synthesis.

The atlas describes physical mechanism families and safe routing metadata.  It
is not a construction manual and deliberately omits hazardous implementation
parameters.
"""

from __future__ import annotations

from .models import Mechanism


MECHANISMS: tuple[Mechanism, ...] = (
    Mechanism(
        "oscillating_charge_current",
        "Oscillating charges and currents",
        1.0,
        3e11,
        "narrowband_or_modulated",
        ("partial", "high"),
        ("loop or dipole antenna", "patch antenna", "phased array", "guided aperture"),
        ("electrical drive to current distribution",),
        ("lumped circuit", "method of moments", "FDTD", "FEM"),
        ("oscilloscope", "spectrum analyzer", "field probe", "network analyzer"),
        ("regulated_transmitter", "rf_exposure", "emc"),
        "low_power_benchtop",
    ),
    Mechanism(
        "dielectric_magnetic_resonance",
        "Dielectric and magnetic resonance",
        1e6,
        3e12,
        "resonant",
        ("partial", "high"),
        ("dielectric resonator", "ferrite resonator", "cavity source"),
        ("driven polarization or magnetization",),
        ("eigenmode solver", "FDTD", "FEM"),
        ("network analyzer", "spectrum analyzer", "near-field probe"),
        ("rf_exposure", "emc", "strong_magnetic_field"),
        "certified_module",
    ),
    Mechanism(
        "electronic_frequency_multiplication",
        "Electronic frequency multiplication",
        1e8,
        3e13,
        "harmonic_comb",
        ("partial", "high"),
        ("frequency multiplier chain", "nonlinear diode module"),
        ("electrical oscillator to harmonics",),
        ("harmonic balance", "nonlinear circuit", "electromagnetic co-simulation"),
        ("spectrum analyzer", "power meter", "harmonic receiver"),
        ("rf_exposure", "emc", "high_voltage"),
        "certified_module",
    ),
    Mechanism(
        "photomixing",
        "Photomixing and optical beating",
        1e10,
        3e13,
        "tunable_narrowband",
        ("high",),
        ("photomixer", "photoconductive emitter"),
        ("optical frequency difference to terahertz current",),
        ("carrier transport", "Maxwell", "thermal model"),
        ("terahertz detector", "electro-optic sampler", "power meter"),
        ("laser", "high_voltage", "terahertz_exposure"),
        "institutional_facility",
    ),
    Mechanism(
        "thermal_emission",
        "Thermal fluctuation emission",
        1e8,
        3e15,
        "broadband",
        ("incoherent",),
        ("blackbody reference", "resistive emitter", "selective thermal surface"),
        ("heat to fluctuating polarization currents",),
        ("Planck spectrum", "fluctuational electrodynamics", "thermal FEM"),
        ("radiometer", "FTIR", "spectrometer", "thermopile"),
        ("hot_surface", "fire", "optical_exposure"),
        "low_power_benchtop",
    ),
    Mechanism(
        "molecular_rotation",
        "Molecular rotational transitions",
        1e8,
        3e13,
        "line_spectrum",
        ("incoherent", "partial"),
        ("molecular gas cell", "maser medium"),
        ("collisional, electrical or optical excitation",),
        ("rate equations", "density matrix", "line-shape model"),
        ("microwave spectrometer", "heterodyne receiver"),
        ("pressurized_gas", "chemical", "rf_exposure"),
        "institutional_facility",
    ),
    Mechanism(
        "molecular_vibration",
        "Molecular vibrational and rovibrational transitions",
        1e11,
        2e14,
        "line_or_band_spectrum",
        ("incoherent", "partial", "high"),
        ("infrared molecular source", "gas laser", "vibrational emitter"),
        ("thermal, electrical or optical excitation",),
        ("rate equations", "density matrix", "radiative transfer"),
        ("FTIR", "infrared spectrometer", "thermal detector"),
        ("chemical", "laser", "pressurized_gas"),
        "certified_module",
    ),
    Mechanism(
        "atomic_ionic_transition",
        "Atomic and ionic electronic transitions",
        1e13,
        3e16,
        "line_spectrum",
        ("incoherent", "partial", "high"),
        ("spectral lamp", "discharge source", "atomic laser"),
        ("electrical, collision or optical pumping",),
        ("rate equations", "density matrix", "collisional-radiative model"),
        ("optical spectrometer", "photodiode", "calibrated radiometer"),
        ("high_voltage", "uv_exposure", "hot_surface", "pressurized_gas"),
        "certified_module",
    ),
    Mechanism(
        "semiconductor_recombination",
        "Semiconductor electron-hole recombination",
        1e12,
        3e15,
        "band_or_narrowband",
        ("incoherent", "partial", "high"),
        ("LED", "OLED", "laser diode", "quantum-well emitter"),
        ("electrical or optical injection to recombination",),
        ("drift diffusion", "rate equations", "Maxwell", "thermal model"),
        ("spectrometer", "photodiode", "integrating sphere", "power meter"),
        ("laser", "uv_exposure", "thermal"),
        "low_power_benchtop",
    ),
    Mechanism(
        "stimulated_emission_maser",
        "Stimulated microwave emission",
        1e5,
        3e12,
        "coherent_narrowband",
        ("high",),
        ("maser", "solid-state spin maser"),
        ("population inversion to coherent microwave field",),
        ("Maxwell-Bloch", "rate equations", "cavity eigenmodes"),
        ("heterodyne receiver", "spectrum analyzer", "frequency counter"),
        ("strong_magnetic_field", "rf_exposure", "cryogenic"),
        "institutional_facility",
    ),
    Mechanism(
        "stimulated_emission_laser",
        "Stimulated optical emission",
        1e12,
        3e16,
        "coherent_narrowband_or_comb",
        ("high",),
        ("solid-state laser", "fiber laser", "semiconductor laser", "gas laser"),
        ("pump energy to population inversion and cavity mode",),
        ("Maxwell-Bloch", "rate equations", "cavity eigenmodes", "thermal model"),
        ("optical spectrum analyzer", "power meter", "beam profiler", "frequency reference"),
        ("laser", "high_voltage", "chemical", "fire"),
        "certified_module",
    ),
    Mechanism(
        "nonlinear_frequency_conversion",
        "Nonlinear optical frequency conversion",
        1e10,
        3e17,
        "harmonic_or_mixed",
        ("partial", "high"),
        ("harmonic generator", "parametric converter", "supercontinuum module"),
        ("sum, difference, harmonic and four-wave mixing",),
        ("nonlinear wave equation", "coupled-mode model", "FDTD"),
        ("spectrometer", "autocorrelator", "power meter", "frequency counter"),
        ("laser", "uv_exposure", "high_field"),
        "institutional_facility",
    ),
    Mechanism(
        "plasma_emission",
        "Plasma line, continuum and collective emission",
        1e5,
        3e19,
        "line_and_continuum",
        ("incoherent", "partial", "high"),
        ("plasma source", "discharge lamp", "laser-produced plasma facility"),
        ("collective oscillation, recombination and collision emission",),
        ("Maxwell-fluid", "PIC", "collisional-radiative", "radiation transport"),
        ("spectrometer", "interferometer", "radiometer", "particle diagnostics"),
        ("plasma", "high_voltage", "uv_exposure", "ionizing_radiation"),
        "institutional_facility",
    ),
    Mechanism(
        "cyclotron_gyrotron",
        "Cyclotron, electron-cyclotron and gyrotron emission",
        1e5,
        3e12,
        "narrowband_or_harmonic",
        ("partial", "high"),
        ("cyclotron source", "gyrotron", "magnetized plasma source"),
        ("charged-particle orbital acceleration",),
        ("Lorentz dynamics", "PIC", "cavity eigenmodes"),
        ("heterodyne receiver", "spectrum analyzer", "field probe"),
        ("strong_magnetic_field", "high_voltage", "high_power_microwave"),
        "institutional_facility",
    ),
    Mechanism(
        "synchrotron_undulator",
        "Synchrotron, wiggler and undulator emission",
        1e7,
        3e21,
        "broadband_or_quasi_monochromatic",
        ("partial", "high"),
        ("synchrotron facility", "undulator beamline", "free-electron laser"),
        ("relativistic charged-particle acceleration",),
        ("relativistic particle tracking", "Lienard-Wiechert fields", "radiation transport"),
        ("beamline spectrometer", "dosimeter", "calorimeter"),
        ("accelerator", "ionizing_radiation", "strong_magnetic_field", "high_voltage"),
        "institutional_facility",
    ),
    Mechanism(
        "bremsstrahlung",
        "Bremsstrahlung from charged-particle deceleration",
        1e13,
        1e22,
        "broadband_continuum",
        ("incoherent",),
        ("regulated X-ray source", "accelerator target"),
        ("energetic charged particles to braking radiation",),
        ("Monte Carlo transport", "relativistic scattering", "radiation transport"),
        ("spectrometer", "ionization chamber", "dosimeter"),
        ("ionizing_radiation", "high_voltage", "accelerator"),
        "institutional_facility",
    ),
    Mechanism(
        "cherenkov",
        "Cherenkov emission",
        1e11,
        3e19,
        "broadband_directional",
        ("partial",),
        ("particle detector radiator", "regulated accelerator diagnostic"),
        ("charged particle exceeding medium phase velocity",),
        ("particle transport", "dispersive Maxwell", "Monte Carlo transport"),
        ("spectrometer", "photomultiplier", "timing detector"),
        ("ionizing_radiation", "accelerator", "high_voltage"),
        "institutional_facility",
    ),
    Mechanism(
        "transition_smith_purcell",
        "Transition, dielectric and Smith-Purcell emission",
        1e8,
        3e15,
        "broadband_or_grating_selected",
        ("partial", "high"),
        ("regulated particle-interface source", "grating emission experiment"),
        ("charged particle interacting with interface or periodic structure",),
        ("particle tracking", "Maxwell", "boundary integral"),
        ("spectrometer", "bolometer", "particle diagnostic"),
        ("accelerator", "high_voltage", "ionizing_radiation"),
        "institutional_facility",
    ),
    Mechanism(
        "nuclear_transition",
        "Nuclear transition gamma emission",
        1e18,
        1e25,
        "line_or_cascade_spectrum",
        ("incoherent",),
        ("licensed nuclear source", "regulated reactor or accelerator facility"),
        ("nuclear excitation and de-excitation",),
        ("nuclear level model", "Monte Carlo transport", "decay-chain model"),
        ("gamma spectrometer", "dosimeter", "calorimeter"),
        ("radioactive_material", "ionizing_radiation", "nuclear"),
        "institutional_facility",
    ),
    Mechanism(
        "particle_annihilation",
        "Particle-antiparticle annihilation radiation",
        1e18,
        1e25,
        "line_and_continuum",
        ("incoherent",),
        ("regulated particle physics or medical facility",),
        ("particle-antiparticle energy to photons",),
        ("relativistic kinematics", "Monte Carlo transport", "detector response"),
        ("gamma spectrometer", "coincidence detector", "dosimeter"),
        ("ionizing_radiation", "radioactive_material", "accelerator"),
        "institutional_facility",
    ),
)


def mechanism_atlas() -> tuple[dict[str, object], ...]:
    return tuple(mechanism.to_dict() for mechanism in MECHANISMS)


def search_mechanisms(query: str) -> tuple[Mechanism, ...]:
    terms = tuple(term.lower() for term in query.split() if term.strip())
    if not terms:
        return MECHANISMS
    matches = []
    for mechanism in MECHANISMS:
        haystack = " ".join(
            (
                mechanism.mechanism_id,
                mechanism.label,
                mechanism.spectral_character,
                *mechanism.device_families,
                *mechanism.conversion_paths,
                *mechanism.simulation_models,
                *mechanism.hazards,
                *mechanism.notes,
            )
        ).lower()
        if all(term in haystack for term in terms):
            matches.append(mechanism)
    return tuple(matches)
