"""Finite permutation-group closure for ROOTFLOW monodromy generators."""

from __future__ import annotations

from dataclasses import dataclass
from collections import deque
from typing import Iterable

Permutation = tuple[int, ...]


def validate_permutation(permutation: Iterable[int]) -> Permutation:
    perm = tuple(int(value) for value in permutation)
    if not perm:
        raise ValueError("permutation must be non-empty")
    if tuple(sorted(perm)) != tuple(range(len(perm))):
        raise ValueError("permutation must contain each index exactly once")
    return perm


def identity_permutation(degree: int) -> Permutation:
    if degree <= 0:
        raise ValueError("degree must be positive")
    return tuple(range(degree))


def compose_permutations(left: Iterable[int], right: Iterable[int]) -> Permutation:
    """Return left ∘ right: apply right first, then left."""
    a = validate_permutation(left)
    b = validate_permutation(right)
    if len(a) != len(b):
        raise ValueError("permutations must have equal degree")
    return tuple(a[b[index]] for index in range(len(a)))


def inverse_permutation(permutation: Iterable[int]) -> Permutation:
    perm = validate_permutation(permutation)
    inverse = [0] * len(perm)
    for index, image in enumerate(perm):
        inverse[image] = index
    return tuple(inverse)


def permutation_cycles(permutation: Iterable[int]) -> tuple[tuple[int, ...], ...]:
    perm = validate_permutation(permutation)
    visited: set[int] = set()
    cycles: list[tuple[int, ...]] = []
    for start in range(len(perm)):
        if start in visited:
            continue
        cycle: list[int] = []
        current = start
        while current not in visited:
            visited.add(current)
            cycle.append(current)
            current = perm[current]
        if len(cycle) > 1:
            cycles.append(tuple(cycle))
    return tuple(cycles)


@dataclass(frozen=True)
class MonodromyGroup:
    degree: int
    generators: tuple[Permutation, ...]
    elements: tuple[Permutation, ...]
    order: int
    transitive: bool
    orbit_of_zero: tuple[int, ...]
    status: str
    theorem_claimed: bool = False
    scientific_validation_claimed: bool = False

    def to_dict(self) -> dict[str, object]:
        return {
            "degree": self.degree,
            "generators": [list(item) for item in self.generators],
            "generator_cycles": [
                [list(cycle) for cycle in permutation_cycles(item)] for item in self.generators
            ],
            "elements": [list(item) for item in self.elements],
            "order": self.order,
            "transitive": self.transitive,
            "orbit_of_zero": list(self.orbit_of_zero),
            "status": self.status,
            "theorem_claimed": self.theorem_claimed,
            "scientific_validation_claimed": self.scientific_validation_claimed,
        }


def generate_monodromy_group(
    generators: Iterable[Iterable[int]],
    *,
    maximum_order: int = 40320,
) -> MonodromyGroup:
    """Compute the finite subgroup generated by supplied branch permutations.

    ``maximum_order`` is a hard OAK resource bound.  The routine refuses to
    claim closure if enumeration exceeds it.
    """
    generator_tuple = tuple(validate_permutation(item) for item in generators)
    if not generator_tuple:
        raise ValueError("at least one generator is required")
    degree = len(generator_tuple[0])
    if any(len(item) != degree for item in generator_tuple):
        raise ValueError("all generators must have equal degree")
    if maximum_order <= 0:
        raise ValueError("maximum_order must be positive")

    identity = identity_permutation(degree)
    closure: set[Permutation] = {identity}
    queue: deque[Permutation] = deque([identity])
    moves = tuple(dict.fromkeys(generator_tuple + tuple(inverse_permutation(g) for g in generator_tuple)))

    while queue:
        current = queue.popleft()
        for generator in moves:
            candidate = compose_permutations(generator, current)
            if candidate in closure:
                continue
            closure.add(candidate)
            if len(closure) > maximum_order:
                raise RuntimeError(
                    "monodromy group enumeration exceeded maximum_order before closure"
                )
            queue.append(candidate)

    ordered = tuple(sorted(closure))
    orbit = tuple(sorted({element[0] for element in ordered}))
    transitive = len(orbit) == degree
    return MonodromyGroup(
        degree=degree,
        generators=generator_tuple,
        elements=ordered,
        order=len(ordered),
        transitive=transitive,
        orbit_of_zero=orbit,
        status="OAK_PASS_MONODROMY_GROUP_CLOSURE",
    )
