"""Conservative proof-assistant skeleton export."""
from __future__ import annotations

import re

from .models import Claim, FormalSkeleton


_NAME = re.compile(r"[^A-Za-z0-9_]")


def _safe_name(value: str) -> str:
    value = _NAME.sub("_", value.strip())
    value = re.sub(r"_+", "_", value).strip("_")
    if not value:
        value = "unnamed_claim"
    if value[0].isdigit():
        value = "claim_" + value
    return value


def export_lean_skeleton(claim: Claim) -> FormalSkeleton:
    theorem_name = _safe_name(claim.claim_id)
    assumptions = tuple(_safe_name(item) for item in claim.assumptions)
    binders = " ".join(f"({name} : Prop)" for name in assumptions)
    premises = " ∧ ".join(assumptions) if assumptions else "True"
    text = (
        f"-- Generated by Ω-MILLENNIUM-T∞. This is a skeleton, not a proof.\n"
        f"theorem {theorem_name} {binders} : ({premises}) → Prop := by\n"
        f"  intro h\n"
        f"  -- Original mathematical statement:\n"
        f"  -- {claim.statement.replace(chr(10), ' ')}\n"
        f"  sorry\n"
    )
    obligations = (
        "replace Prop placeholder with a faithful formal statement",
        "formalize every mathematical object and domain assumption",
        "discharge the generated sorry without untrusted axioms",
        "independently audit correspondence with the original claim",
    )
    return FormalSkeleton(
        language="lean4",
        theorem_name=theorem_name,
        text=text,
        unresolved_obligations=obligations,
        proof_complete=False,
    )
