"""Ω-CAPABILITY-OS-T∞: capability planning, bounded execution and external receipts."""

from .bridge import WorkUnitBridge, compile_workunit, workunit_from_mapping
from .chatmem import (
    ChatMemCheckpointManifest,
    chatmem_bootstrap_intent,
    chatmem_capabilities,
    chatmem_checkpoint_intent,
    chatmem_external_bindings,
    checkpoint_gate_handler,
    default_chatmem_bootstrap_values,
)
from .core import (
    Capability,
    Intent,
    make_evidence_receipt,
    outcome_record,
    plan,
    suggest_fallback,
    validate_registry,
)
from .drift import (
    DRIFT_SCHEMA_VERSION,
    DriftCase,
    DriftFixture,
    benchmark_fixture,
    benchmark_fixture_corpus,
    generate_drift_cases,
    load_fixture_corpus,
    load_fixture_corpus_file,
)
from .external import (
    ExternalActionReceipt,
    ExternalActionRequest,
    ExternalBinding,
    ExternalResolver,
    load_external_bindings,
    make_external_request,
    validate_external_bindings,
    validate_external_receipt,
)
from .github_memory import (
    CapabilityGraph,
    CapabilityRequest,
    GitHubMemoryIndex,
    GitHubPRSource,
    ReuseBeforeCreateGate,
    build_live_index,
)
from .github_memory_evolution import (
    CrossRepositoryCapabilityGraph,
    LLMTFederationCompiler,
    LLMTIdentity,
    ResidualArtifactSpec,
    ResidualCodeCompiler,
    ReuseOutcomeLearner,
    ReuseOutcomeReceipt,
    SupersessionCandidate,
    TemporalSupersessionMiner,
    compile_evolution_court,
)
from .github_memory_zoom import (
    ProgressiveGitHubRetriever,
    ProgressiveRetrievalReceipt,
    SymbolObservation,
    extract_python_symbols,
)
from .normalizers import (
    NORMALIZER_SCHEMA_VERSION,
    ProviderResponseNormalizationError,
    ResponseContract,
    normalize_calendar_response,
    normalize_drive_response,
    normalize_files_response,
    normalize_github_response,
    normalize_gmail_response,
    normalize_provider_response,
    normalize_web_response,
)
from .runtime import ActionRequired, CapabilityRuntime, HandlerResult, learn_health

__all__ = [
    "Capability",
    "Intent",
    "plan",
    "suggest_fallback",
    "validate_registry",
    "make_evidence_receipt",
    "outcome_record",
    "WorkUnitBridge",
    "compile_workunit",
    "workunit_from_mapping",
    "ActionRequired",
    "CapabilityRuntime",
    "HandlerResult",
    "learn_health",
    "ExternalBinding",
    "ExternalActionRequest",
    "ExternalActionReceipt",
    "ExternalResolver",
    "load_external_bindings",
    "make_external_request",
    "validate_external_bindings",
    "validate_external_receipt",
    "NORMALIZER_SCHEMA_VERSION",
    "ProviderResponseNormalizationError",
    "ResponseContract",
    "normalize_provider_response",
    "normalize_github_response",
    "normalize_files_response",
    "normalize_drive_response",
    "normalize_gmail_response",
    "normalize_calendar_response",
    "normalize_web_response",
    "DRIFT_SCHEMA_VERSION",
    "DriftCase",
    "DriftFixture",
    "generate_drift_cases",
    "benchmark_fixture",
    "benchmark_fixture_corpus",
    "load_fixture_corpus",
    "load_fixture_corpus_file",
    "ChatMemCheckpointManifest",
    "chatmem_capabilities",
    "chatmem_external_bindings",
    "chatmem_bootstrap_intent",
    "chatmem_checkpoint_intent",
    "checkpoint_gate_handler",
    "default_chatmem_bootstrap_values",
    "CapabilityRequest",
    "GitHubMemoryIndex",
    "CapabilityGraph",
    "ReuseBeforeCreateGate",
    "GitHubPRSource",
    "build_live_index",
    "ProgressiveGitHubRetriever",
    "ProgressiveRetrievalReceipt",
    "SymbolObservation",
    "extract_python_symbols",
    "SupersessionCandidate",
    "TemporalSupersessionMiner",
    "ResidualArtifactSpec",
    "ResidualCodeCompiler",
    "ReuseOutcomeReceipt",
    "ReuseOutcomeLearner",
    "CrossRepositoryCapabilityGraph",
    "LLMTIdentity",
    "LLMTFederationCompiler",
    "compile_evolution_court",
]
__version__ = "0.7.0"
