"""Generate reproducible Tristan Runtime bundle plans from immutable evidence locks.

The R0.8 bundle contains the *current* runtime wheel built from the checked-out
source plus public peer wheels built from immutable commits. The R0.8 integration
lock remains an evidence receipt for the older runtime commit actually exercised
by the four-repository matrix. Those roles are intentionally distinct.
"""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any

from .integration_r08 import DEFAULT_R08_LOCK, R08IntegrationLock


@dataclass(frozen=True, slots=True)
class BundleFiles:
    directory: Path
    manifest: Path
    public_requirements: Path
    private_extension_requirements: Path | None

    def to_dict(self) -> dict[str, str | None]:
        return {
            "directory": str(self.directory),
            "manifest": str(self.manifest),
            "public_requirements": str(self.public_requirements),
            "private_extension_requirements": str(self.private_extension_requirements) if self.private_extension_requirements else None,
        }


class BundlePlan:
    """Side-effect-bounded current-runtime bundle planner."""

    current_runtime_distribution = "omega-ai-tristan-lab"
    current_runtime_version = "0.8.0"

    def __init__(self, lock: R08IntegrationLock = DEFAULT_R08_LOCK):
        lock.validate()
        self.lock = lock

    def public_peer_targets(self) -> tuple[str, ...]:
        return tuple(peer.pip_target for peer in self.lock.peers if peer.visibility == "public")

    def manifest(self) -> dict[str, Any]:
        return {
            "bundle_schema": "tristan-runtime-bundle-plan-0.1",
            "current_runtime": {
                "distribution": self.current_runtime_distribution,
                "version": self.current_runtime_version,
                "source_mode": "build-wheel-from-current-checkout",
            },
            "verified_environment_evidence": self.lock.to_dict(),
            "public_peer_build_targets": list(self.public_peer_targets()),
            "private_extension_targets": list(self.lock.private_extension_targets()),
            "build_policy": {
                "network_on_import": False,
                "automatic_install": False,
                "automatic_publish": False,
                "private_targets_in_public_lock": False,
                "wheelhouse_expected": True,
                "peer_source_refs_immutable": True,
                "verified_runtime_is_not_silently_substituted_for_current_runtime": True,
            },
            "oak_rule": (
                "The evidence lock proves an earlier exact runtime environment; the current v0.8 wheel must pass its own CI. "
                "A bundle plan is a reproducibility recipe, not scientific certification."
            ),
        }

    def public_requirements_text(self) -> str:
        lines = [
            "# Generated by Ω-TRISTAN-RUNTIME BundlePlan v0.8",
            "# Build omega-ai-tristan-lab==0.8.0 from the current checkout; these are exact public peer sources.",
        ]
        lines.extend(self.public_peer_targets())
        return "\n".join(lines) + "\n"

    def private_extension_requirements_text(self) -> str:
        lines = [
            "# Private extension targets; explicit authenticated installation required.",
            "# Keep this file out of public distribution when it reveals private repository topology.",
        ]
        lines.extend(self.lock.private_extension_targets())
        return "\n".join(lines) + "\n"

    def materialize(self, directory: str | Path, *, include_private_extension: bool = False) -> BundleFiles:
        root = Path(directory)
        root.mkdir(parents=True, exist_ok=True)
        manifest_path = root / "bundle-manifest.json"
        public_path = root / "requirements-public.lock"
        private_path = root / "requirements-private-extension.lock" if include_private_extension else None
        manifest_path.write_text(json.dumps(self.manifest(), ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        public_path.write_text(self.public_requirements_text(), encoding="utf-8")
        if private_path is not None:
            private_path.write_text(self.private_extension_requirements_text(), encoding="utf-8")
        return BundleFiles(root, manifest_path, public_path, private_path)
