"""Workspace persistence for Ω-AI-TRISTAN-LAB v0.2."""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .agent_harness import AgentHarness
from .ingest import DocumentIngestor
from .rag_engine import MiniRAG
from .reporting import ReportRenderer


@dataclass(frozen=True)
class WorkspaceRun:
    """Paths generated by one workspace run."""

    run_dir: Path
    json_report: Path
    markdown_report: Path
    manifest: Path


class Workspace:
    """Run Ω-AI-Tristan pipelines and persist artifacts."""

    def __init__(self, root: str | Path = "omega_runs") -> None:
        self.root = Path(root)
        self.renderer = ReportRenderer()
        self.harness = AgentHarness()
        self.ingestor = DocumentIngestor()

    def run_idea(self, idea: str, name: str | None = None) -> WorkspaceRun:
        report = self.harness.run(idea)
        return self.persist_report(report, name=name or str(report["theory_card"].name))

    def run_with_documents(
        self,
        idea: str,
        document_paths: list[str | Path],
        context_query: str | None = None,
        name: str | None = None,
    ) -> WorkspaceRun:
        rag = MiniRAG()
        ingested = self.ingestor.ingest_many(document_paths)
        chunks_total = 0
        warnings: list[str] = []
        for document in ingested:
            warnings.extend([f"{document.source_path}: {warning}" for warning in document.warnings])
            for chunk in self.ingestor.chunk_document(document):
                rag.add_text(chunk.text, source=chunk.id)
                chunks_total += 1

        context = rag.answer_context(context_query or idea, top_k=5)
        enriched_idea = (
            f"{idea}\n\nLocal context summary for OAK/RAG use:\n{context}\n\n"
            f"Ingested documents: {len(ingested)}; chunks: {chunks_total}; warnings: {warnings}"
        )
        report = self.harness.run(enriched_idea)
        report["ingestion"] = {
            "documents": [document.__dict__ for document in ingested],
            "chunks_total": chunks_total,
            "warnings": warnings,
            "context_query": context_query or idea,
            "retrieved_context": context,
        }
        return self.persist_report(report, name=name or str(report["theory_card"].name))

    def persist_report(self, report: dict[str, Any], name: str | None = None) -> WorkspaceRun:
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        slug = self._slugify(name or "omega-ai-tristan-run")
        run_dir = self.root / f"{timestamp}_{slug}"
        json_path = run_dir / "report.json"
        markdown_path = run_dir / "report.md"
        manifest_path = run_dir / "manifest.txt"

        self.renderer.write_json(report, json_path)
        self.renderer.write_markdown(report, markdown_path)
        manifest_path.write_text(
            "\n".join([
                "Ω-AI-TRISTAN-LAB Workspace Run",
                f"timestamp_utc={timestamp}",
                f"slug={slug}",
                f"json_report={json_path.name}",
                f"markdown_report={markdown_path.name}",
                "oak_rule=no merge/public claim without tests, limits, IP gate, and residuals",
                "",
            ]),
            encoding="utf-8",
        )
        return WorkspaceRun(
            run_dir=run_dir,
            json_report=json_path,
            markdown_report=markdown_path,
            manifest=manifest_path,
        )

    @staticmethod
    def _slugify(value: str) -> str:
        value = value.lower().strip()
        value = re.sub(r"[^a-z0-9]+", "-", value)
        value = re.sub(r"-+", "-", value).strip("-")
        return value[:80] or "omega-ai-tristan-run"
