"""Ω-PURE-MATH-T∞: executable pure-mathematics research kernel."""

from .bracket_spectrum import (
    BracketSpectrum,
    Leaf,
    Node,
    all_parenthesizations,
    associativity_defect,
    bracket_spectrum,
    edge_associator_field,
    evaluate_tree,
    rotation_graph,
    rotation_graph_connected,
    rotation_neighbors,
    tree_signature,
    zero_triple_defect_on,
)
from .core import (
    Claim,
    ClaimStatus,
    OAKFinding,
    OAKReport,
    TheorySpec,
    fertile_compression_score,
    invariant_defect,
    law_defect,
    oak_audit_claims,
)
from .dimension_spectrum import DimensionFunctional, DimensionSpectrum, dimension_spectrum
from .factor_bricks import (
    BrickLanguage,
    FactorizationWitness,
    compose_witnesses,
    minimum_recorded_length,
    subadditivity_certificate,
)
from .factor_tree import FactorTree, factor_tree_distance, minimum_factor_tree
from .finite_classification import (
    invariant_collisions,
    invariant_is_complete,
    minimal_complete_invariant_families,
    orbit,
    orbit_partition,
)
from .hgfm_formal import (
    HGFM,
    HypergraphLevel,
    ScaleMap,
    compose_scale_maps,
    growth_dimension,
    scale_coherence_defect,
)
from .invariants import (
    Invariant,
    InvariantComparison,
    compare_invariants,
    cvcd_matrix,
    invariant_preorder,
)
from .logexp_adapter import (
    LogarithmGate,
    LogExpRoundTrip,
    generator_round_trip,
    near_identity_log_gate,
)
from .negative_math import (
    NegativeMathEntry,
    NegativeMathRegistry,
    minimal_sufficient_subsets,
)
from .proof_geometry import (
    Inference,
    ProofHypergraph,
    expected_proof_cost,
    proof_free_energy,
    proof_partition_function,
)
from .representation_geometry import (
    RepresentationGraph,
    RepresentationScore,
    dominates,
    pareto_front,
)
from .residuals import (
    ResidualStep,
    geometric_residual_bound,
    residual_tower,
    uniformly_contracting,
)
from .structural_dna import StructuralDNA
from .tensor_spectrum import (
    TensorChannel,
    TensorSpectrum,
    channel_dimension_conservation,
    custom_tensor_spectrum,
    second_tensor_power_spectrum,
)
from .theorem_protocol import (
    MUTATION_AXES,
    QUESTION_KINDS,
    THEOREM_CANDIDATES,
    ResearchQuestion,
    generate_research_protocol,
    protocol_as_dict,
)
from .theory_evolution import (
    FiniteTheory,
    symmetric_difference_distance,
    theory_intersection,
)
from .zero_tomography import (
    Grid,
    discrete_laplacian,
    log_modulus_grid,
    source_density,
    strongest_interior_sources,
)

__all__ = [
    "BracketSpectrum",
    "BrickLanguage",
    "Claim",
    "ClaimStatus",
    "DimensionFunctional",
    "DimensionSpectrum",
    "FactorTree",
    "FactorizationWitness",
    "FiniteTheory",
    "Grid",
    "HGFM",
    "HypergraphLevel",
    "Inference",
    "Invariant",
    "InvariantComparison",
    "Leaf",
    "LogExpRoundTrip",
    "LogarithmGate",
    "MUTATION_AXES",
    "NegativeMathEntry",
    "NegativeMathRegistry",
    "Node",
    "OAKFinding",
    "OAKReport",
    "ProofHypergraph",
    "QUESTION_KINDS",
    "RepresentationGraph",
    "RepresentationScore",
    "ResearchQuestion",
    "ResidualStep",
    "ScaleMap",
    "StructuralDNA",
    "THEOREM_CANDIDATES",
    "TensorChannel",
    "TensorSpectrum",
    "TheorySpec",
    "all_parenthesizations",
    "associativity_defect",
    "bracket_spectrum",
    "channel_dimension_conservation",
    "compare_invariants",
    "compose_scale_maps",
    "compose_witnesses",
    "custom_tensor_spectrum",
    "cvcd_matrix",
    "dimension_spectrum",
    "discrete_laplacian",
    "dominates",
    "edge_associator_field",
    "evaluate_tree",
    "expected_proof_cost",
    "factor_tree_distance",
    "fertile_compression_score",
    "generate_research_protocol",
    "generator_round_trip",
    "geometric_residual_bound",
    "growth_dimension",
    "invariant_collisions",
    "invariant_defect",
    "invariant_is_complete",
    "invariant_preorder",
    "law_defect",
    "log_modulus_grid",
    "minimal_complete_invariant_families",
    "minimal_sufficient_subsets",
    "minimum_factor_tree",
    "minimum_recorded_length",
    "near_identity_log_gate",
    "oak_audit_claims",
    "orbit",
    "orbit_partition",
    "pareto_front",
    "proof_free_energy",
    "proof_partition_function",
    "protocol_as_dict",
    "residual_tower",
    "rotation_graph",
    "rotation_graph_connected",
    "rotation_neighbors",
    "scale_coherence_defect",
    "second_tensor_power_spectrum",
    "source_density",
    "strongest_interior_sources",
    "subadditivity_certificate",
    "symmetric_difference_distance",
    "theory_intersection",
    "tree_signature",
    "uniformly_contracting",
    "zero_triple_defect_on",
]
