"""Ω-CYBER-PHYSICAL-SYSTEMS-T: OAK-safe whole-system research kernels."""

from .compiler import (
    MOTION_TYPES,
    PrototypeArchitecture,
    PrototypeCandidate,
    PrototypeCompilationReport,
    PrototypeIntent,
    compile_prototype,
    default_prototype_architectures,
    demo_integrated_robot_intent,
)
from .control import PIDConfig, PIDState, PIDStep, pid_step
from .cosim import (
    AxisPlantConfig,
    ClosedLoopReport,
    ClosedLoopSample,
    ClosedLoopScenario,
    ElectronicsConfig,
    FaultEvent,
    SafetyLimits,
    demo_fault_scenario,
    demo_nominal_scenario,
    run_closed_loop_axis,
)
from .dynamics import (
    SimulationSample,
    SimulationTrace,
    StateSpaceModel,
    dc_motor_model,
    electromechanical_axis_model,
    mass_spring_damper_model,
    rk4_step,
    simulate_state_space,
)
from .evidence import (
    EVIDENCE_TIERS,
    ReceiptAssessment,
    SystemEvidenceLedger,
    SystemEvidenceReceipt,
    assess_evidence_ledger,
    assess_receipt,
    computational_demo_receipts,
)
from .fault_analysis import FaultPropagationRecord, FaultPropagationReport, analyze_fault_propagation
from .inventory import (
    DOMAIN_KEYWORDS,
    InventoryConfig,
    RepositoryInventoryReport,
    RepositorySystemRecord,
    discover_repository_systems,
    summarize_inventory,
)
from .models import (
    COMPARATORS,
    DOMAINS,
    PORT_DIRECTIONS,
    Component,
    Connection,
    FaultMode,
    Port,
    Requirement,
    SystemBlueprint,
    demo_electromechanical_axis_blueprint,
)
from .oak import CPSOAKGate, CPSOAKReport, run_cps_benchmarks

__all__ = [
    "AxisPlantConfig",
    "COMPARATORS",
    "CPSOAKGate",
    "CPSOAKReport",
    "ClosedLoopReport",
    "ClosedLoopSample",
    "ClosedLoopScenario",
    "Component",
    "Connection",
    "DOMAINS",
    "DOMAIN_KEYWORDS",
    "EVIDENCE_TIERS",
    "ElectronicsConfig",
    "FaultEvent",
    "FaultMode",
    "FaultPropagationRecord",
    "FaultPropagationReport",
    "InventoryConfig",
    "MOTION_TYPES",
    "PIDConfig",
    "PIDState",
    "PIDStep",
    "PORT_DIRECTIONS",
    "Port",
    "PrototypeArchitecture",
    "PrototypeCandidate",
    "PrototypeCompilationReport",
    "PrototypeIntent",
    "ReceiptAssessment",
    "RepositoryInventoryReport",
    "RepositorySystemRecord",
    "Requirement",
    "SafetyLimits",
    "SimulationSample",
    "SimulationTrace",
    "StateSpaceModel",
    "SystemBlueprint",
    "SystemEvidenceLedger",
    "SystemEvidenceReceipt",
    "analyze_fault_propagation",
    "assess_evidence_ledger",
    "assess_receipt",
    "compile_prototype",
    "computational_demo_receipts",
    "dc_motor_model",
    "default_prototype_architectures",
    "demo_electromechanical_axis_blueprint",
    "demo_fault_scenario",
    "demo_integrated_robot_intent",
    "demo_nominal_scenario",
    "discover_repository_systems",
    "electromechanical_axis_model",
    "mass_spring_damper_model",
    "pid_step",
    "rk4_step",
    "run_closed_loop_axis",
    "run_cps_benchmarks",
    "simulate_state_space",
    "summarize_inventory",
]

__version__ = "0.1.0"
