"""Ω-CYBER-PHYSICAL-SYSTEMS-T: OAK-safe whole-system research kernels."""

from .compiler import (
    MOTION_TYPES,
    PrototypeArchitecture,
    PrototypeCandidate,
    PrototypeCompilationReport,
    PrototypeIntent,
    compile_prototype,
    default_prototype_architectures,
    demo_integrated_robot_intent,
)
from .control import PIDConfig, PIDState, PIDStep, pid_step
from .cosim import (
    AxisPlantConfig,
    ClosedLoopReport,
    ClosedLoopSample,
    ClosedLoopScenario,
    ElectronicsConfig,
    FaultEvent,
    SafetyLimits,
    demo_fault_scenario,
    demo_nominal_scenario,
    run_closed_loop_axis,
)
from .dynamics import (
    SimulationSample,
    SimulationTrace,
    StateSpaceModel,
    dc_motor_model,
    electromechanical_axis_model,
    mass_spring_damper_model,
    rk4_step,
    simulate_state_space,
)
from .energy_graph import (
    DomainBalance,
    EnergyGraphReport,
    EnergyTerm,
    PassivityAssessment,
    audit_closed_loop_energy,
)
from .evidence import (
    EVIDENCE_TIERS,
    ReceiptAssessment,
    SystemEvidenceLedger,
    SystemEvidenceReceipt,
    assess_evidence_ledger,
    assess_receipt,
    computational_demo_receipts,
)
from .fault_analysis import FaultPropagationRecord, FaultPropagationReport, analyze_fault_propagation
from .inventory import (
    DOMAIN_KEYWORDS,
    InventoryConfig,
    RepositoryInventoryReport,
    RepositorySystemRecord,
    discover_repository_systems,
    summarize_inventory,
)
from .models import (
    COMPARATORS,
    DOMAINS,
    PORT_DIRECTIONS,
    Component,
    Connection,
    FaultMode,
    Port,
    Requirement,
    SystemBlueprint,
    demo_electromechanical_axis_blueprint,
)
from .oak import CPSOAKGate, CPSOAKReport, run_cps_benchmarks
from .r02_oak import CPSR02OAKGate, CPSR02OAKReport, run_cps_r02_benchmarks
from .unit_graph import (
    DIMENSION_NAMES,
    POWER_DIMENSION,
    ConnectionUnitAssessment,
    DomainPortSemantics,
    PortUnitAssessment,
    UnitDefinition,
    UnitGraphReport,
    UnitRegistry,
    audit_blueprint_units,
    default_domain_semantics,
    default_unit_registry,
)

__all__ = [
    "AxisPlantConfig",
    "COMPARATORS",
    "CPSOAKGate",
    "CPSOAKReport",
    "CPSR02OAKGate",
    "CPSR02OAKReport",
    "ClosedLoopReport",
    "ClosedLoopSample",
    "ClosedLoopScenario",
    "Component",
    "Connection",
    "ConnectionUnitAssessment",
    "DIMENSION_NAMES",
    "DOMAINS",
    "DOMAIN_KEYWORDS",
    "DomainBalance",
    "DomainPortSemantics",
    "EVIDENCE_TIERS",
    "ElectronicsConfig",
    "EnergyGraphReport",
    "EnergyTerm",
    "FaultEvent",
    "FaultMode",
    "FaultPropagationRecord",
    "FaultPropagationReport",
    "InventoryConfig",
    "MOTION_TYPES",
    "PIDConfig",
    "PIDState",
    "PIDStep",
    "PORT_DIRECTIONS",
    "POWER_DIMENSION",
    "PassivityAssessment",
    "Port",
    "PortUnitAssessment",
    "PrototypeArchitecture",
    "PrototypeCandidate",
    "PrototypeCompilationReport",
    "PrototypeIntent",
    "ReceiptAssessment",
    "RepositoryInventoryReport",
    "RepositorySystemRecord",
    "Requirement",
    "SafetyLimits",
    "SimulationSample",
    "SimulationTrace",
    "StateSpaceModel",
    "SystemBlueprint",
    "SystemEvidenceLedger",
    "SystemEvidenceReceipt",
    "UnitDefinition",
    "UnitGraphReport",
    "UnitRegistry",
    "analyze_fault_propagation",
    "assess_evidence_ledger",
    "assess_receipt",
    "audit_blueprint_units",
    "audit_closed_loop_energy",
    "compile_prototype",
    "computational_demo_receipts",
    "dc_motor_model",
    "default_domain_semantics",
    "default_prototype_architectures",
    "default_unit_registry",
    "demo_electromechanical_axis_blueprint",
    "demo_fault_scenario",
    "demo_integrated_robot_intent",
    "demo_nominal_scenario",
    "discover_repository_systems",
    "electromechanical_axis_model",
    "mass_spring_damper_model",
    "pid_step",
    "rk4_step",
    "run_closed_loop_axis",
    "run_cps_benchmarks",
    "run_cps_r02_benchmarks",
    "simulate_state_space",
    "summarize_inventory",
]

__version__ = "0.2.0"
