const C={modes:["SAGE Architect","OAK Verifier","GitHub Builder","Publication Atlas","Open Data Harvester","Spectro Lab","Math Proof","AIT Router","Canonizer"],intents:["chat answer","GitHub files","workflow","test suite","schema","dataset manifest","publication package","benchmark","proof sketch","OAK review","HGFM graph"],oak:["OAK-1 idea","OAK-2 definition","OAK-3 scaffold","OAK-4 prototype","OAK-5 measurement","OAK-6+ review"],branches:["TFUGA","TGTM","HGFM","CVCD","OAK","SAGE","AIT","Bayes-Tristan","FFWT-HAC-CVCD","Publication Atlas","Open Data Harvester","Publication Package Factory","AIT-Universe","Math Universe","Spectro Universe","Materials","AI7","M+","M−"],github:["create files","add tests","add workflow","add docs","add runbook","add schema","add benchmark","verify with fetch_file","upload artifact"]};
const S={branches:new Set(["TFUGA","HGFM","OAK","SAGE","Bayes-Tristan","M−"]),github:new Set(["create files","add tests","add workflow","verify with fetch_file"]),claims:[]};
const $=id=>document.getElementById(id);function toast(t){const e=$("toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function fillSelect(id,items){$(id).innerHTML=items.map(x=>`<option>${x}</option>`).join("")}function chip(root,item,set){const b=document.createElement("button");b.className=`chip ${set.has(item)?"active":""}`;b.textContent=item;b.onclick=()=>{set.has(item)?set.delete(item):set.add(item);render();};root.appendChild(b)}
function checks(root,item,set){const b=document.createElement("button");b.className=`check ${set.has(item)?"active":""}`;b.textContent=item;b.onclick=()=>{set.has(item)?set.delete(item):set.add(item);render();};root.appendChild(b)}
function payload(){return{version:"chatgpt-tristan-session.v2",title:$("title").value,mode:$("mode").value,intent:$("intent").value,format:$("format").value,oak_target:$("oak").value,mission:$("mission").value,constraints:$("constraints").value,branches:[...S.branches],github_actions:[...S.github],positive_memory:$("mplus").value.split("\n").filter(Boolean),negative_memory:$("mminus").value.split("\n").filter(Boolean),claims:S.claims,repo:$("repo").value,data_theory:$("dataTheory").value,data_mode:$("dataMode").value,publication_scope:$("pubScope").value,publication_output:$("pubOutput").value,created_at:new Date().toISOString()}}
function compile(){const p=payload();const compact=p.format==="compact";let lines=[`# ${p.title}`,`Mode: ${p.mode}`,`Artifact intent: ${p.intent}`,`OAK target: ${p.oak_target}`,"",`Mission: ${p.mission}`,"",`Branches: ${p.branches.join(", ")}`,`Contraintes: ${p.constraints}`,"",`M+: ${p.positive_memory.join("; ")||"none"}`,`M−: ${p.negative_memory.join("; ")||"none"}`,""];if(!compact){lines.push("## Obligations","- Répondre en français.","- ZÉRO-TOUCH si les outils le permettent.","- Distinguer vision, formalisation, prototype, mesure, preuve.","- Ajouter résidus M−, tests, limites et statut OAK.","- Ne pas promettre de travail futur; produire maintenant.","- Si GitHub est disponible: créer fichiers, tests, workflows, docs, puis vérifier.","");}
if(p.format==="github-action")lines.push("## GitHub action",`Repo: ${p.repo}`,`Actions: ${p.github_actions.join(", ")}`,"Créer artifacts vérifiables et citer les fichiers fetch_file.");
if(p.mode.includes("Publication"))lines.push("## Publication boundary","Aucun envoi automatique. Match ≠ endorsement. Review humaine obligatoire.");
if(p.mode.includes("Data"))lines.push("## Data boundary","Licence, provenance, taille et manifest obligatoires avant toute validation.");
if(p.claims.length)lines.push("## Claims matrix",...p.claims.map(c=>`- [${c.oak}] ${c.type}: ${c.claim}`));
$("prompt").value=lines.join("\n");return $("prompt").value}
function addOak(){S.claims.push({claim:$("claim").value,type:$("claimType").value,oak:$("oak").value,residues:["requires review"],tests:[]});renderClaims();compile();toast("OAK card ajoutée")}
function renderClaims(){const r=$("claimsMatrix");r.innerHTML="";S.claims.forEach((c,i)=>{const d=document.createElement("div");d.className="item";d.innerHTML=`<strong>${c.oak}</strong> · ${c.type}<br>${c.claim}<br><button data-i="${i}">supprimer</button>`;d.querySelector("button").onclick=()=>{S.claims.splice(i,1);renderClaims();compile()};r.appendChild(d)});if(!S.claims.length)r.innerHTML='<p class="note">Aucune OAK card pour l’instant.</p>'}
function graph(){const nodes=["Mission",...S.branches,"OAK",$("intent").value,"M−"];const edges=nodes.slice(1).map(n=>["Mission",n]);$("graphText").textContent=JSON.stringify({version:"hgfm.local.v1",nodes,edges},null,2);const svg=$("graphSvg");svg.innerHTML="";const cx=450,cy=260,r=190;nodes.forEach((n,i)=>{const a=(i/nodes.length)*Math.PI*2;const x=i?cx+Math.cos(a)*r:cx,y=i?cy+Math.sin(a)*r:cy;if(i){svg.innerHTML+=`<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="#8aa4ff66"/>`}svg.innerHTML+=`<circle cx="${x}" cy="${y}" r="32" fill="#72f7d422" stroke="#72f7d4aa"/><text x="${x}" y="${y+52}" text-anchor="middle" fill="#eef6ff" font-size="13">${n}</text>`})}
function preset(kind){if(kind==="github"){$("mode").value="GitHub Builder";$("intent").value="GitHub files";$("format").value="github-action";$("mission").value="Créer une amélioration complète dans mon repo avec fichiers, tests, workflow, docs, runbook, schémas et vérification fetch_file."}if(kind==="data"){$("mode").value="Open Data Harvester";$("intent").value="dataset manifest";$("mission").value="Créer un pipeline de recherche/téléchargement borné de data open-source avec licences, provenance, manifest et benchmark OAK."}if(kind==="publication"){$("mode").value="Publication Atlas";$("intent").value="publication package";$("mission").value="Générer des packages de publication review-only pour universités/professeurs/recherches avec OAK, M−, dataset plan et prototype plan."}compile();toast("Preset chargé")}
function save(){localStorage.setItem("chatgpt-tristan-v2:last",JSON.stringify(payload(),null,2));toast("Session locale sauvée");sessions()}function sessions(){const v=localStorage.getItem("chatgpt-tristan-v2:last");$("savedSessions").innerHTML=v?`<div class="item"><strong>Dernière session</strong><br>${JSON.parse(v).title}<br><button id="loadLast">Charger</button></div>`:'<p class="note">Aucune session locale.</p>';const b=$("loadLast");if(b)b.onclick=()=>load(JSON.parse(v))}
function load(p){$("title").value=p.title||"Session";$("mode").value=p.mode||C.modes[0];$("intent").value=p.intent||C.intents[0];$("format").value=p.format||"detailed";$("oak").value=p.oak_target||C.oak[3];$("mission").value=p.mission||"";$("constraints").value=p.constraints||"";S.branches=new Set(p.branches||[]);S.github=new Set(p.github_actions||[]);S.claims=p.claims||[];$("mplus").value=(p.positive_memory||[]).join("\n");$("mminus").value=(p.negative_memory||[]).join("\n");render();compile()}function download(name,obj){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:"application/json"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function critique(){S.claims.push({claim:"Auto-OAK critique: vérifier claims forts, datasets, licence, baseline, preuve, permissions et absence d’envoi automatique.",type:"review",oak:$("oak").value,residues:["auto-generated critique"],tests:["baseline","license review","counterexample search"]});renderClaims();compile();toast("Critique OAK ajoutée")}
function render(){["mode","intent","oak","dataTheory"].forEach((id,i)=>fillSelect(id,[C.modes,C.intents,C.oak,["omega_math_universe","omega_spectro_universe","omega_materials","ait_dynamics","bayes_tristan","hgfm","bio_hgfm"]][i]));const br=$("branches");br.innerHTML="";C.branches.forEach(x=>chip(br,x,S.branches));const ga=$("githubActions");ga.innerHTML="";C.github.forEach(x=>checks(ga,x,S.github));renderClaims();sessions();compile()}
document.querySelectorAll(".rail button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".rail button,.tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")});document.querySelectorAll("[data-preset]").forEach(b=>b.onclick=()=>preset(b.dataset.preset));["title","mode","intent","format","oak","mission","constraints","mplus","mminus","repo","dataTheory","dataMode","pubScope","pubOutput"].forEach(id=>$(id).addEventListener("input",compile));$("compileBtn").onclick=()=>{compile();toast("Prompt compilé")};$("copyBtn").onclick=async()=>{await navigator.clipboard.writeText(compile());toast("Prompt copié")};$("criticBtn").onclick=critique;$("addOakCard").onclick=addOak;$("buildGraph").onclick=graph;$("saveLocal").onclick=save;$("exportJson").onclick=()=>download("chatgpt-tristan-session-v2.json",payload());$("exportOak").onclick=()=>download("oak-cards.json",{version:"oak-cards.v1",claims:S.claims});$("clearLocal").onclick=()=>{localStorage.removeItem("chatgpt-tristan-v2:last");sessions();toast("Local effacé")};render();graph();