"""Ω-META-SCIENCE-FOUNDRY-T∞² executable research kernel."""

from .benchmark import build_fixture, run_benchmark, run_strategy
from .discovery import (
    ArbitrageDecision,
    CounterexampleCandidate,
    DiscoveryDynamicsReport,
    EpistemicJacobianReport,
    InvariantTransportMap,
    InvariantTransportReport,
    RepresentationRoute,
    ResidualGenome,
    ScientificIR,
    TheoryAdapter,
    compile_counterexample,
    compile_residual_genome,
    epistemic_jacobian,
    representation_arbitrage,
    run_discovery_dynamics_demo,
    transport_invariants,
    unknown_unknown_radar,
)
from .geometry import (
    AdversarialTwinReport,
    ClaimConstraint,
    DiscoveryGeometryAlgebraReport,
    EpistemicHessianReport,
    EvidenceIndependenceReport,
    ScientificProgram,
    ScientificSuperoptimizerReport,
    TheoryEquivalenceClass,
    TheoryQuotientReport,
    TransformCertificate,
    TransformCertificateReport,
    UnsatCoreReport,
    compile_adversarial_twin,
    empirical_theory_quotient,
    epistemic_hessian,
    evidence_independence,
    minimal_unsat_core,
    run_discovery_geometry_algebra_demo,
    scientific_superoptimize,
    validate_transform_certificate,
)
from .models import BenchmarkReport, Experiment, StrategyResult, TheoryGenome
from .oak import FAULT_TYPES, evaluate_oak, meta_oak_mutation_campaign

__all__ = [
    "AdversarialTwinReport",
    "ArbitrageDecision",
    "BenchmarkReport",
    "ClaimConstraint",
    "CounterexampleCandidate",
    "DiscoveryDynamicsReport",
    "DiscoveryGeometryAlgebraReport",
    "EpistemicHessianReport",
    "EpistemicJacobianReport",
    "EvidenceIndependenceReport",
    "Experiment",
    "FAULT_TYPES",
    "InvariantTransportMap",
    "InvariantTransportReport",
    "RepresentationRoute",
    "ResidualGenome",
    "ScientificIR",
    "ScientificProgram",
    "ScientificSuperoptimizerReport",
    "StrategyResult",
    "TheoryAdapter",
    "TheoryEquivalenceClass",
    "TheoryGenome",
    "TheoryQuotientReport",
    "TransformCertificate",
    "TransformCertificateReport",
    "UnsatCoreReport",
    "build_fixture",
    "compile_adversarial_twin",
    "compile_counterexample",
    "compile_residual_genome",
    "empirical_theory_quotient",
    "epistemic_hessian",
    "epistemic_jacobian",
    "evaluate_oak",
    "evidence_independence",
    "meta_oak_mutation_campaign",
    "minimal_unsat_core",
    "representation_arbitrage",
    "run_benchmark",
    "run_discovery_dynamics_demo",
    "run_discovery_geometry_algebra_demo",
    "run_strategy",
    "scientific_superoptimize",
    "transport_invariants",
    "unknown_unknown_radar",
    "validate_transform_certificate",
]

__version__ = "0.3.0"
