"""Tristan Web OS public seed part 2."""
ROWS = r"""\
omega-mems-cpu-t|Ω-MEMS-CPU-T|MEMS et CPU fractal mycélien|Applique motifs troués, canaux et réseaux multi-échelles aux MEMS, interconnexions, capteurs et refroidissement.|MEMS;microfabrication;matériel|architecture|simulation requise|4|La fabricabilité dépend des outils, matériaux, rendements, overlays, rugosités, contamination et coûts.|Créer une bibliothèque de motifs et un OAKBench lithographie, thermique, RC et variabilité.|docs/theory_cards/OMEGA_MEMS_CPU_T.md|hardware
omega-laser-mems-cpu-t|Ω-LASER-MEMS-CPU-T|Laser pour microfabrication et photonique|Utilise le laser comme outil de mesure, écriture, activation, recuit et correction dans des systèmes microfabriqués.|laser;photonique;microfabrication|architecture|simulation et sécurité|3|Aucune promesse sub-nanométrique arbitraire; diffraction, absorption, dégâts et sécurité oculaire s’appliquent.|Simuler le budget thermique et la résolution d’un motif direct-writing basse énergie.|docs/theory_cards/OMEGA_LASER_MEMS_CPU_T.md|hardware
omega-corp-jarvis-t|Ω-CORP-JARVIS-T|Compagnie-cerveau corporative|Orchestre projets, contrats, IP, tâches, CRM et décisions avec approbation humaine pour les actions sensibles.|entreprise;agents IA;gouvernance|architecture|workflow requis|7|Aucune signature, publication, dépense ou communication externe sensible sans permission explicite.|Implémenter un registre d’actions proposé/approuvé/exécuté avec rollback et journal append-only.|docs/theory_cards/OMEGA_CORP_JARVIS_T.md|venture
omega-lin-t|Ω-LIN-T|Linéarisation multi-échelle|Traite la linéarisation comme atlas de modèles locaux avec domaines de validité et résidus non linéaires conservés.|mathématiques;contrôle;modélisation|architecture|prototype ciblé|6|Une stabilité locale ou un bon ajustement local ne prouve pas un comportement global.|Créer un atlas Jacobien/Koopman et mesurer l’erreur hors domaine sur systèmes non linéaires.|docs/theory_cards/OMEGA_LIN_T.md|science
omega-chem-log-lin-t|Ω-CHEM-LOG-LIN-T|Cinétique chimique en coordonnées logarithmiques|Transforme les lois multiplicatives et vitesses relatives en représentations log pour analyse et approximation.|chimie;EDO;mathématiques|architecture|cas tests requis|5|Toutes les EDO chimiques ne deviennent pas globalement linéaires et les concentrations doivent rester positives.|Comparer réactions d’ordre 1/2, Michaelis–Menten et autocatalyse aux solveurs standards.|docs/theory_cards/OMEGA_CHEM_LOG_LIN_T.md|science
omega-energy-t|Ω-ENERGY-T|Systèmes énergétiques de Tristan|Relie sources, stockage, conversion, réseau, contrôle, pertes, mesure, sécurité et économie dans un microgrid auditable.|énergie;contrôle;simulation|architecture|MVP simulé|7|L’énergie ne se crée pas; tous rendements, pertes, bilans thermiques et incertitudes doivent être explicités.|Livrer un microgrid PV–batterie–charge avec bilan énergétique et baselines de contrôle.|docs/theory_cards/OMEGA_ENERGY_T.md|energy
omega-game-t|Ω-GAME-T|GameEngine et GameMaster de Tristan|Traite règles, mondes, quêtes, narration, économie et agents comme hypergraphe interactif vérifiable.|jeu;simulation;IA|architecture|prototype ludique|5|Éviter dark patterns, manipulation addictive, collecte abusive et confusion entre jeu et preuve scientifique.|Créer un monde minimal déterministe avec journal d’événements, tests de règles et maître de jeu réversible.|docs/theory_cards/OMEGA_GAME_T.md|creative
omega-neg-t|Ω-NEG-T|Néguentropie de Tristan|Mesure l’ordre utile local par compression, prédiction, stabilité et réparation tout en comptant les coûts et dissipations.|thermodynamique;information;complexité|hypothèse|métrique à calibrer|4|Toute baisse d’entropie locale exige un système ouvert, un coût énergétique et un export d’entropie.|Comparer plusieurs indices sur compression, prédiction et auto-réparation de systèmes simulés.|docs/theory_cards/OMEGA_NEG_T.md|science
omega-learn-t|Ω-LEARN-T|Apprentissage de Tristan|Convertit expérience, erreur, attention et pratique en modèles internes testés par rétention, transfert et action.|apprentissage;éducation;IA|architecture|protocoles à tester|6|Il faut distinguer apprentissage humain, machine, métaphore computationnelle et preuve empirique.|Construire un tracker de maîtrise et mesurer rétention, transfert, coût et fatigue.|docs/theory_cards/OMEGA_LEARN_T.md|education
omega-jkd-t|Ω-JKD-T|Interception lucide multi-domaine|Formalise perception précoce, désescalade, sortie, action minimale et apprentissage par résidus.|sécurité;cognition;entraînement|architecture|sécurité d’abord|4|Ce système n’est pas un manuel de blessure ni une garantie de défense; priorité à l’évitement et aux professionnels.|Créer un simulateur de décisions non violentes avec scénarios, sorties et journal M⁻.|docs/theory_cards/OMEGA_JKD_T.md|safety
omega-calib-t|Ω-CALIB-T|Calibrations instrumentales|Relie instrument, référence, procédure, environnement, incertitude, dérive et certificat dans un graphe traçable.|métrologie;instrumentation;qualité|architecture|prototype ciblé|7|Une calibration n’est jamais vérité absolue; domaine, conditions, versions et incertitudes doivent être enregistrés.|Créer un passeport d’instrument et un détecteur de dérive sur données publiques ou synthétiques.|docs/theory_cards/OMEGA_CALIB_T.md|measurement
"""
