"""Tristan Web OS public seed part 3."""
ROWS = r"""\
omega-zeta-mandel-t|Ω-ZETA-MANDEL-T|Zêta–Mandelbrot computationnel|Laboratoire numérique reliant fonctions zêta, dynamiques complexes et algèbres de Cayley–Dickson.|mathématiques;fractales;calcul numérique|prototype|exploration numérique|8|Aucune image, corrélation ou stabilité d’orbite ne constitue une preuve de l’hypothèse de Riemann.|Tester stabilité sous précision, projection, norme, parenthésage et pas numérique.|docs/theory_cards/OMEGA_ZETA_MANDEL_T.md|math
omega-natsci-t|Ω-NATSCI-T|Méta-laboratoire des sciences naturelles|Unifie flux de matière, énergie, information et formes dans des modèles réduits avec provenance et résidus.|sciences naturelles;modélisation;données|architecture|cas réduits requis|6|Analogie, visualisation, simulation, hypothèse, découverte et preuve doivent rester séparées.|Livrer six exemples réduits avec unités, conservation, baseline et prédictions falsifiables.|docs/theory_cards/OMEGA_NATSCI_T.md|science
omega-atlas-t|Ω-ATLAS-T|HyperAtlas polyglotte multi-niveaux|Cartographie connaissances, fichiers, code, agents, droits, preuves, routes d’action et potentiel de valeur.|connaissance;hypergraphe;outillage|architecture|prototype CLI|9|Une carte n’est jamais le territoire; toute route doit conserver provenance, permissions et incertitudes.|Implémenter ingestion Markdown/YAML et produire atlas JSON, GraphML et rapport OAK.|docs/theory_cards/OMEGA_ATLAS_T.md|platform
omega-vtp-t|Ω-VTP-T|Vectorisation, tensorisation et parallélisme|Transforme calculs et graphes en représentations exécutables en parallèle sans perdre précision ni causalité.|calcul haute performance;tensorisation;GPU|architecture|benchmark requis|6|Un speedup apparent peut être annulé par transferts mémoire, overhead, précision ou non-déterminisme.|Comparer CPU scalaire, NumPy et GPU avec exactitude, mémoire, énergie et taille de problème.|docs/theory_cards/OMEGA_VTP_T.md|compute
omega-oss-digest-t|Ω-OSS-DIGEST-T|Digestion open source et Stack Exchange|Absorbe dépôts, licences, issues, tests et connaissances externes avec provenance, sécurité et attribution.|open source;GitHub;supply chain|architecture|prototype ciblé|8|Ne jamais copier aveuglément; licence, attribution, vulnérabilités, secrets et compatibilité doivent être vérifiés.|Créer un pipeline SBOM, licence, provenance, tests sandbox et registre M⁻.|docs/theory_cards/OMEGA_OSS_DIGEST_T.md|developer-tools
omega-pdf-hypergraph-github-t|Ω-PDF-HYPERGRAPH-GITHUB-T|Absorption PDF vers hypergraphe et GitHub|Ingest ZIP/PDF, extrait claims, équations et figures, puis produit graphes, rapports et artefacts traçables.|documents;extraction;hypergraphe|architecture|prototype d’ingestion|10|Chaque extraction doit conserver page, zone, source, confiance, droits et distinction extraction/interprétation.|Tester un corpus contrôlé et mesurer rappel, précision, erreurs d’équations et provenance.|docs/theory_cards/OMEGA_PDF_HYPERGRAPH_GITHUB_T.md|developer-tools
omega-fpg-t|Ω-FPG-T|Groupes ponctuels fractals|Généralise les symétries locales exactes ou approximatives à plusieurs échelles avec métriques et résidus.|mathématiques;symétrie;cristallographie|hypothèse|formalisation requise|3|Un motif visuel ou une invariance numérique n’est pas automatiquement un groupe exact.|Définir espace, action, générateurs, métrique, tolérance et contre-exemples pour un premier cas.|docs/theory_cards/OMEGA_FPG_T.md|math
omega-fcryst-t|Ω-FCRYST-T|Théorie des cristaux fractals|Étudie ordre multi-échelle, défauts, pores, interfaces, diffraction et propriétés de matériaux architecturés.|cristallographie;matériaux;fractales|architecture|simulation et expérience|5|Il faut distinguer cristal classique, quasi-cristal, motif artificiel, modèle et matériau expérimental.|Simuler une structure architecturée et prédire une signature de diffraction mesurable.|docs/theory_cards/OMEGA_FCRYST_T.md|materials
omega-doc-t|Ω-DOC-T|Documentation vivante et exécutable|Traite la documentation comme mémoire versionnée reliant claims, preuves, code, tests, versions et permissions.|documentation;qualité;outillage|architecture|premier produit défini|9|Un document récent peut rester faux; la cohérence avec code, exemples et tests doit être vérifiée.|Construire un audit détectant une divergence réelle entre affirmation, exemple et code.|docs/theory_cards/OMEGA_DOC_T.md|developer-tools
omega-sans-plafond-t|Ω-SANS-PLAFOND-T|Architecture d’itération sans plafond arbitraire|Remplace les limites fixes par budgets adaptatifs, sharding, streaming, backpressure, checkpoints et rollback.|systèmes distribués;scalabilité;automatisation|prototype|frontière finie testée|11|Sans plafond arbitraire ne signifie pas sans limites physiques, coûts, quotas, risques ou contrôle de qualité.|Mesurer la prochaine saturation réelle puis modifier l’architecture plutôt que relever une constante.|docs/theory_cards/OMEGA_SANS_PLAFOND_T.md|platform
omega-mail-t|Ω-MAIL-T|Laboratoire de courriels intercompagnies|Génère et teste des fils de courriels synthétiques entre compagnies et agents dans un transport fermé.|courriel;simulation;agents IA|architecture|MVP fermé|5|Aucun envoi externe, massif ou commercial sans consentement, conformité, throttling et approbation.|Implémenter boîtes en mémoire, scénarios YAML, assertions, erreurs simulées et rapports de couverture.|docs/theory_cards/OMEGA_MAIL_T.md|platform
"""
