"""Tristan Web OS public seed part 4."""
ROWS = r"""\
omega-web-tristan-t|Ω-WEB-TRISTAN-T|Tristan Web OS|Interface publique et privée reliant théories, claims, preuves, code, risques, IP, produits et prochaines actions.|web;connaissance;publication|prototype|R0.2 en construction|14|Le site doit montrer moins de grandeur déclarée et davantage d’artefacts, limites et résultats reproductibles.|Relier chaque carte publique à un claim, une preuve, un test, un commit et une politique de visibilité.|docs/theory_cards/OMEGA_WEB_TRISTAN_T.md|platform
omega-wiki-t|Ω-WIKI-T∞|WikiForge multilingue et sourcé|Lit des articles révisionnés, extrait claims et sources, traduit sous garde-fous et construit des graphes de connaissance.|Wikipedia;sources;multilingue|prototype|extraction traçable|10|Wikipedia n’est pas une certification; une citation présente n’implique pas qu’elle soutient le claim.|Ajouter validation de support claim–source, comparaison de révisions et divergences entre langues.|docs/theory_cards/OMEGA_WIKI_T.md|developer-tools
omega-logexp-morph-t|Ω-LOGEXP-MORPH-T∞²|Calcul des générateurs LOG/EXP|Modélise translations, dilatations, rotations et morphismes par générateurs, exponentielles et résidus.|algèbre;dynamique;calcul scientifique|prototype|noyau testé|12|L’existence d’un logarithme ou d’une représentation ne prouve ni compression utile ni causalité physique.|Ajouter identification parcimonieuse, BCH/Magnus adaptatif et validation hors échantillon.|docs/theory_cards/OMEGA_LOGEXP_MORPH_T.md|math
omega-quaternion-crystal-t|Ω-QUATERNION-CRYSTAL-T|Quaternions, cristaux, déformation et stress|Sépare orientation quaternionique, transformation affine, tenseurs de contrainte/déformation et élasticité.|quaternions;cristallographie;mécanique|prototype|noyau 3D testé|10|Rotation, déformation et contrainte sont des objets distincts; les fusionner sans unités crée des erreurs.|Étendre aux groupes ponctuels, désorientations minimales et champs EBSD avec incertitudes.|docs/theory_cards/OMEGA_QUATERNION_CRYSTAL_T.md|materials
omega-ecc-t|Ω-ECC-T|Correction d’erreurs de Tristan|Relie codes classiques, syndromes, hypergraphes de parité et mémoire négative dans un laboratoire reproductible.|information;codes correcteurs;fiabilité|prototype|tests déterministes|9|Un score de syndrome ne remplace ni preuve de correction générale ni modèle réaliste du canal.|Comparer Hamming, BCH/LDPC simples et canaux burst avec coût, latence et taux résiduel.|docs/theory_cards/OMEGA_ECC_T.md|compute
omega-prime-object-t|Ω-PRIME-OBJECT-T|Objets premiers relatifs|Définit l’irréductibilité relativement à un domaine, une composition, des invariants et des tentatives de factorisation.|mathématiques;algèbre;génération|prototype|noyau et CLI|11|Le score local ne certifie ni primalité absolue, ni preuve, ni potentiel commercial.|Tester plusieurs domaines algébriques et vérifier recomposition, résidus et faux positifs.|docs/theory_cards/OMEGA_PRIME_OBJECT_T.md|math
omega-fact-infinity-t|Ω-FACT∞-T|Factorisation multi-domaine|Décompose objets, opérateurs, invariants et cofactors puis mesure la qualité de recomposition.|mathématiques;décomposition;outillage|prototype|OAKBench local|8|Une décomposition pratique n’est pas nécessairement unique, minimale ou mathématiquement canonique.|Ajouter ambiguïté de factorisation, coût descriptif et comparaison à des décompositions standards.|docs/theory_cards/OMEGA_FACT_INFINITY_T.md|math
omega-generator-discovery-stack|Ω-GENERATOR-DISCOVERY-STACK|Découverte de générateurs et résidus|Couple identification de transformations, spectres, commutateurs, holonomie, protocoles et classement d’expériences.|dynamique;spectres;expérimentation|prototype|dix fronts exécutables|16|Reconstruction, compression, prédiction, causalité et validation expérimentale sont des niveaux distincts.|Ajouter Jacobiennes analytiques, incertitudes, cross-validation et baselines physiques.|docs/theory_cards/OMEGA_GENERATOR_DISCOVERY_STACK.md|science
omega-life-t|Ω-VIE-T∞|Vie, abiogenèse et évolution|Organise chimie prébiotique, évolution, transitions biologiques, cognition et technosphère dans un graphe de recherche.|biologie;évolution;systèmes complexes|architecture|recherche exploratoire|5|Aucune expérience n’a reconstruit tout le passage continu de la géochimie abiotique à une cellule autonome.|Créer une chronologie sourcée et un simulateur réduit de réseaux autocatalytiques sans prétention d’abiogenèse complète.|docs/theory_cards/OMEGA_VIE_T.md|life-science
omega-edu-can-qc-t|Ω-EDU-CAN-QC-T|HyperSystème éducatif Québec–Canada|Cartographie programmes, diplômes, cours, compétences, prérequis, équivalences et preuves d’apprentissage.|éducation;Québec;connaissance|architecture|ingestion progressive|7|Le système ne doit pas imposer une fausse uniformité nationale ni remplacer les sources institutionnelles officielles.|Ingest un petit ensemble de programmes officiels avec dates, juridictions et provenance.|docs/theory_cards/OMEGA_EDU_CAN_QC_T.md|education
omega-algorithmic-energy-t|Ω-ALGO-ENERGY-T|Énergie et entropie algorithmique|Explore des métriques de coût computationnel, information utile, dissipation et néguentropie de calcul.|algorithmique;énergie;information|hypothèse|définitions à stabiliser|3|Les métaphores thermodynamiques ne deviennent pas automatiquement des grandeurs physiques mesurables.|Séparer énergie matérielle mesurée, complexité, entropie informationnelle et heuristiques de fertilité.|docs/theory_cards/OMEGA_ALGO_ENERGY_T.md|compute
"""
