"""Tristan Web OS public seed part 1."""
ROWS = r"""\
omega-tristan-self-os|Ω-TRISTAN-SELF-OS|Système opératoire de cristallisation|Transforme l’expansion conceptuelle en définitions, preuves, code, tests, actifs, offres et décisions traçables.|méta-système;recherche;entrepreneuriat|architecture|structuration|8|L’efficacité doit être mesurée par le débit d’artefacts fermés, pas par le nombre de branches nommées.|Mesurer chaque semaine le ratio idées capturées / artefacts vérifiables livrés.|docs/00_MASTER_CANON_TFUGA_AI7_AIT.md|platform
omega-transform-t|Ω-TRANSFORM-T|Transformées multi-échelles de Tristan|Relie FWT, extensions fractales, tensorisation et analyse multi-échelle pour compression, reconstruction et détection.|mathématiques;signal;IA|prototype|test partiel|12|La pondération fractale naïve n’a pas battu la FWT standard sur le premier benchmark de reconstruction.|Comparer sur anomalies, débruitage, classification et coût de calcul.|docs/theory_cards/OMEGA_TRANSFORM_T.md|science
omega-unc2-t|Ω-UNC²-T|Incertitude de l’incertitude|Structure provenance, calibration, résidus, désaccords de modèles et décisions robustes contre la surconfiance.|épistémologie;statistiques;IA|architecture|pré-prototype|5|Les niveaux d’incertitude proposés doivent être calibrés sur des décisions et jeux de données réels.|Implémenter un registre U² et tester sa calibration sur des claims de dépôts.|docs/theory_cards/OMEGA_UNC2_T.md|governance
omega-cvcd-t|Ω-CVCD-T|Calcul virtuel compressé-décompressé|Explore un espace de possibilités sous forme comprimée puis décompresse seulement les régions prometteuses et vérifiables.|calcul;optimisation;IA|hypothèse|benchmark requis|4|Une reconstruction plausible ou compacte ne constitue ni une vérité, ni une preuve, ni un optimum global.|Comparer à la recherche exhaustive, au beam search et à l’échantillonnage bayésien.|docs/theory_cards/OMEGA_CVCD_T.md|compute
omega-cpufmt|Ω-CPUFMT|CPU fractal mycélien|Architecture de calcul modulaire explorant topologies NoC, caches multi-échelles, redondance et contrôle thermo-énergétique.|matériel;RISC-V;systèmes|architecture|simulation requise|3|Aucune supériorité PPA, thermique ou manufacturière n’est revendiquée avant synthèse, simulation et comparaison.|Construire un simulateur de topologies et comparer latence, énergie, surface et tolérance aux défauts.|docs/theory_cards/OMEGA_CPUFMT.md|hardware
omega-bat-t|Ω-BAT-T|Batteries de Tristan|Modélise les batteries comme systèmes électro-chemo-thermo-mécaniques avec diagnostic, BMS, vieillissement et sécurité.|énergie;matériaux;contrôle|architecture|simulation requise|6|Simulation-first; aucune instruction de fabrication ou manipulation dangereuse de cellules et packs.|Créer un analyseur EIS public avec baselines, incertitudes et détection de dérive.|docs/theory_cards/OMEGA_BAT_T.md|energy
omega-3dp-t|Ω-3DP-T|Fabrication additive vérifiable|Relie géométrie, matériau, procédé, trajectoire, capteurs, défauts et métrologie dans un jumeau numérique auditable.|fabrication;matériaux;métrologie|architecture|pré-prototype|4|Une pièce imprimée n’est pas une pièce qualifiée; essais, tolérances et traçabilité restent indispensables.|Générer des coupons de calibration et mesurer anisotropie, porosité et gauchissement.|docs/theory_cards/OMEGA_3DP_T.md|manufacturing
omega-company-qc-ca-t|Ω-COMPANY-QC-CA-T|Compagnie et usine d’actifs Québec–Canada|Convertit les actifs scientifiques en offres, pilotes et produits avec gouvernance, propriété intellectuelle et conformité.|entrepreneuriat;Québec;gouvernance|architecture|validation marché requise|9|Aucun revenu ni marché n’est présumé; une offre, un client et un usage répété sont les premiers tests.|Cristalliser une offre d’audit OAK, la tester avec un pilote et mesurer le temps économisé.|docs/COMPANY_REVENUE_IP_PUBLICATION_OS.md|venture
omega-neuro-t|Ω-NEURO-T|Neurosciences hypergraphiques|Formalise cognition, mémoire, attention, action et apprentissage comme hypergraphe dynamique multi-échelle.|neurosciences;cognition;modélisation|architecture|recherche seulement|4|Ce cadre n’est ni un diagnostic, ni une prescription, ni une preuve clinique; les analogies doivent rester falsifiables.|Construire un notebook sur données publiques et séparer faits établis, modèle et hypothèses.|docs/theory_cards/OMEGA_NEURO_T.md|health-research
omega-oem-mtd-t|Ω-OEMMTD-T|Opto-électro-magnéto-mécano-thermodynamique|Couple lumière, champs, charges, déformation, chaleur et transitions de phase dans des modèles multi-physiques.|physique;matériaux;multi-physique|architecture|réduction aux cas connus|4|Toute extension doit respecter unités, conservation, entropie non négative et validation expérimentale.|Implémenter un cas piézoélectrique ou thermoélectrique réduit et comparer à un solveur de référence.|docs/theory_cards/OMEGA_OEMMTD_T.md|science
omega-opt-solar-t|Ω-OPT-SOLAR-T|Miroir fractal troué solaire|Explore des surfaces optiques multi-échelles où trous, canaux et étages redistribuent un flux solaire mesurable.|optique;solaire;géométrie|architecture|ray tracing requis|5|Le concept ne contourne ni diffraction, ni étendue optique, ni pertes, ni limites thermiques.|Construire un ray tracer et comparer PSF, flux utile, tolérance d’alignement et température.|docs/theory_cards/OMEGA_OPT_SOLAR_T.md|energy
"""
