import {auditClaim,claimPassport,localFingerprint,mutateClaim,parseCsv,supportScore} from "./kernel.mjs";
const $=s=>document.querySelector(s);const tabs=[...document.querySelectorAll("[data-tab]")];const panels=[...document.querySelectorAll("[data-panel]")];
tabs.forEach(btn=>btn.addEventListener("click",()=>{tabs.forEach(x=>x.classList.toggle("active",x===btn));panels.forEach(p=>p.hidden=p.dataset.panel!==btn.dataset.tab);}));
function evidenceFromForm(scope){const type=$("#evidenceType").value;if(type==="NONE")return[];return[{id:"E-local-1",type,source:$("#evidenceSource").value||"local-user-input",scope,independent:$("#independent").checked,strength:Number($("#strength").value)}];}
function buildClaim(){const scope=parseCsv($("#scope").value);return{id:$("#claimId").value.trim()||"AX-T-LOCAL",statement:$("#statement").value.trim(),kind:$("#kind").value,domain:$("#domain").value.trim()||"unspecified",definitions:parseCsv($("#definitions").value),scope,assumptions:parseCsv($("#assumptions").value),evidence:evidenceFromForm(scope),counterevidence:[],uncertainty:{model:Number($("#uncertainty").value)},falsifiers:parseCsv($("#falsifiers").value),proofObligations:parseCsv($("#proofObligations").value),provenance:parseCsv($("#provenance").value),status:$("#status").value,version:"0.1.0-local",generatorId:$("#generator").value.trim(),judgeId:$("#judge").value.trim(),revenueScore:Number($("#revenue").value||0)};}
function render(){const claim=buildClaim();const report=auditClaim(claim);const passport=claimPassport(claim);const mutations=mutateClaim(claim).map(x=>({id:x.id,mutation:x.mutation,statement:x.statement,scope:x.scope,heuristicSupport:supportScore(x),authoritative:false}));$("#oakSummary").className=`pill ${report.passed?"pass":"fail"}`;$("#oakSummary").textContent=report.passed?"OAK PASS (local structural)":"OAK HOLD";$("#gates").innerHTML=report.results.map(r=>`<li class="${r.passed?"ok":"bad"}"><strong>${r.passed?"PASS":"HOLD"}</strong> ${r.gate}<span>${r.reason}</span></li>`).join("");$("#passport").textContent=JSON.stringify(passport,null,2);$("#mutations").innerHTML=mutations.map(m=>`<article class="mutation"><div><span class="tag">${m.mutation}</span><span class="tag ghost">${m.id}</span></div><h3>${escapeHtml(m.statement)}</h3><p>Scope: ${m.scope.join(" · ")||"none"}</p><p>Heuristic support: ${m.heuristicSupport} — <strong>non-authoritative</strong></p></article>`).join("");$("#claimFingerprint").textContent=localFingerprint(JSON.stringify(claim));renderGraph(claim,mutations);}
function renderGraph(claim,mutations){const center=`<div class="node root"><b>${escapeHtml(claim.id)}</b><small>${escapeHtml(claim.kind)}</small></div>`;const children=mutations.map(m=>`<div class="node"><b>${escapeHtml(m.id)}</b><small>${escapeHtml(m.mutation)}</small></div>`).join("");$("#graph").innerHTML=`<div class="graph-root">${center}<div class="edge"></div><div class="children">${children}</div></div>`;}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
$("#compile").addEventListener("click",render);$("#loadSample").addEventListener("click",()=>{$("#claimId").value="AX-T-SAMPLE-001";$("#statement").value="A bounded modular architecture can preserve declared service under a single declared component failure.";$("#domain").value="distributed-systems";$("#definitions").value="service = declared critical function remains available, single-fault = one declared component removed";$("#scope").value="single-fault, bounded-topology";$("#assumptions").value="failure independence is not presumed";$("#falsifiers").value="find an admissible single-fault case whose service loss exceeds the baseline criterion";$("#provenance").value="sample:axiome-tristan-r01";$("#evidenceType").value="BENCHMARK";$("#evidenceSource").value="sample:fixture-baseline";$("#status").value="TESTED";$("#generator").value="generator-A";$("#judge").value="judge-B";render();});render();
