from __future__ import annotations

from .models import SourceProfile


BEST_SITES_V1: tuple[SourceProfile, ...] = (
    SourceProfile(
        source_id="wikimedia",
        name="Wikimedia projects",
        tier=0,
        authority_score=0.94,
        domains=("wikipedia.org", "wikidata.org", "wikimedia.org"),
        modes=("api", "dump"),
        endpoints=("https://www.wikidata.org/w/api.php", "https://dumps.wikimedia.org/"),
        access_state="ready",
        full_text_policy="licensed_only",
        license_note="Per-project and per-item free licenses; attribution and share-alike may apply.",
        policy_url="https://www.mediawiki.org/wiki/Wikimedia_APIs/Access_policy",
        refresh_days=7,
        requests_per_second=1.0,
        pilot_budget=250,
        topics=("encyclopedia", "entities", "citations", "multilingual"),
        notes="Prefer dumps for bulk; identify the client and preserve license metadata.",
    ),
    SourceProfile(
        source_id="openalex",
        name="OpenAlex",
        tier=0,
        authority_score=0.96,
        domains=("openalex.org", "api.openalex.org"),
        modes=("api", "dump"),
        endpoints=("https://api.openalex.org/works", "https://developers.openalex.org/download/overview"),
        access_state="key_required",
        full_text_policy="metadata_only",
        license_note="Open scholarly graph metadata; use snapshot for large-scale local analysis.",
        policy_url="https://developers.openalex.org/api-reference/authentication",
        refresh_days=30,
        requests_per_second=1.0,
        pilot_budget=500,
        topics=("papers", "authors", "institutions", "citations", "topics"),
        required_env=("OPENALEX_API_KEY",),
    ),
    SourceProfile(
        source_id="crossref",
        name="Crossref",
        tier=0,
        authority_score=0.97,
        domains=("crossref.org", "api.crossref.org"),
        modes=("api", "dump"),
        endpoints=("https://api.crossref.org/works",),
        access_state="ready",
        full_text_policy="metadata_only",
        license_note="Most bibliographic metadata is reusable; abstracts may retain publisher copyright.",
        policy_url="https://www.crossref.org/documentation/retrieve-metadata/rest-api/access-and-authentication/",
        refresh_days=7,
        requests_per_second=0.5,
        pilot_budget=500,
        topics=("doi", "bibliography", "licenses", "funders", "retractions"),
        notes="Use a contact-bearing User-Agent or mailto, caching and exponential backoff.",
    ),
    SourceProfile(
        source_id="pubmed",
        name="PubMed",
        tier=0,
        authority_score=0.98,
        domains=("pubmed.ncbi.nlm.nih.gov", "eutils.ncbi.nlm.nih.gov"),
        modes=("api", "dump"),
        endpoints=("https://eutils.ncbi.nlm.nih.gov/entrez/eutils/", "https://pubmed.ncbi.nlm.nih.gov/download/"),
        access_state="ready",
        full_text_policy="metadata_only",
        license_note="Citations and abstracts are distributed under PubMed data terms; article full text is separate.",
        policy_url="https://pubmed.ncbi.nlm.nih.gov/download/",
        refresh_days=1,
        requests_per_second=0.3,
        pilot_budget=300,
        topics=("medicine", "biology", "clinical", "citations", "mesh"),
    ),
    SourceProfile(
        source_id="pmc_open",
        name="PubMed Central reusable subset",
        tier=0,
        authority_score=0.97,
        domains=("pmc.ncbi.nlm.nih.gov",),
        modes=("oai",),
        endpoints=("https://pmc.ncbi.nlm.nih.gov/api/oai/v1/mh/",),
        access_state="ready",
        full_text_policy="open_only",
        license_note="Harvest metadata broadly; ingest full text only where item rights explicitly permit reuse.",
        policy_url="https://pmc.ncbi.nlm.nih.gov/tools/oai/",
        refresh_days=7,
        requests_per_second=0.2,
        pilot_budget=150,
        topics=("open_access", "biomedicine", "full_text", "citations"),
    ),
    SourceProfile(
        source_id="arxiv",
        name="arXiv",
        tier=0,
        authority_score=0.95,
        domains=("arxiv.org", "export.arxiv.org"),
        modes=("api", "dump"),
        endpoints=("https://export.arxiv.org/api/query", "https://info.arxiv.org/help/bulk_data_s3.html"),
        access_state="review_required",
        full_text_policy="metadata_only",
        license_note="Paper licenses vary by submission; metadata-first until current bulk/API terms are reviewed.",
        policy_url="https://info.arxiv.org/help/api/index.html",
        refresh_days=7,
        requests_per_second=0.2,
        pilot_budget=200,
        topics=("physics", "mathematics", "computer_science", "quantitative_science"),
    ),
    SourceProfile(
        source_id="nist_pdr",
        name="NIST Public Data Repository",
        tier=0,
        authority_score=0.99,
        domains=("data.nist.gov",),
        modes=("api", "web"),
        endpoints=("https://data.nist.gov/rmm/records", "https://data.nist.gov/pdr/"),
        access_state="ready",
        full_text_policy="open_only",
        license_note="Public technical metadata and datasets; retain record-level terms, DOI and citation.",
        policy_url="https://data.nist.gov/pdr/",
        refresh_days=30,
        requests_per_second=0.5,
        pilot_budget=200,
        topics=("standards", "materials", "measurements", "engineering", "datasets"),
    ),
    SourceProfile(
        source_id="nasa_open",
        name="NASA Open APIs",
        tier=1,
        authority_score=0.98,
        domains=("api.nasa.gov", "nasa.gov"),
        modes=("api",),
        endpoints=("https://api.nasa.gov/",),
        access_state="key_required",
        full_text_policy="metadata_only",
        license_note="Government data access varies by service; preserve endpoint-specific attribution and terms.",
        policy_url="https://api.nasa.gov/",
        refresh_days=7,
        requests_per_second=0.2,
        pilot_budget=100,
        topics=("space", "astronomy", "earth_observation", "missions"),
        required_env=("NASA_API_KEY",),
    ),
    SourceProfile(
        source_id="cern_open_data",
        name="CERN Open Data Portal",
        tier=0,
        authority_score=0.99,
        domains=("opendata.cern.ch", "repository.cern"),
        modes=("api", "oai", "web"),
        endpoints=("https://opendata.cern.ch/api/records", "https://repository.cern/api/records"),
        access_state="ready",
        full_text_policy="open_only",
        license_note="Open datasets and software with record-level licenses and recommended citations.",
        policy_url="https://opendata.cern.ch/docs/about",
        refresh_days=30,
        requests_per_second=0.3,
        pilot_budget=200,
        topics=("particle_physics", "detectors", "software", "datasets"),
    ),
    SourceProfile(
        source_id="usgs",
        name="U.S. Geological Survey APIs",
        tier=1,
        authority_score=0.98,
        domains=("usgs.gov", "data.usgs.gov"),
        modes=("api", "web"),
        endpoints=("https://www.usgs.gov/products/web-tools/apis", "https://data.usgs.gov/datacatalog/"),
        access_state="ready",
        full_text_policy="metadata_only",
        license_note="Authoritative government metadata; dataset-level access and terms vary by product.",
        policy_url="https://www.usgs.gov/products/web-tools/apis",
        refresh_days=7,
        requests_per_second=0.5,
        pilot_budget=200,
        topics=("earthquakes", "water", "geology", "maps", "climate"),
    ),
    SourceProfile(
        source_id="esa_cci",
        name="ESA Climate Change Initiative Open Data",
        tier=1,
        authority_score=0.97,
        domains=("climate.esa.int", "data.cci.ceda.ac.uk", "data.esa.int"),
        modes=("api", "web"),
        endpoints=("https://archive.opensearch.ceda.ac.uk/opensearch/description.xml", "https://data.esa.int/"),
        access_state="ready",
        full_text_policy="metadata_only",
        license_note="Use open catalogue protocols; retain dataset-level licenses and provenance.",
        policy_url="https://climate.esa.int/en/data/",
        refresh_days=30,
        requests_per_second=0.2,
        pilot_budget=150,
        topics=("climate", "earth_observation", "satellites", "environment"),
    ),
    SourceProfile(
        source_id="canada_open",
        name="Government of Canada Open Data",
        tier=0,
        authority_score=0.99,
        domains=("open.canada.ca", "ouvert.canada.ca"),
        modes=("api", "web"),
        endpoints=("https://open.canada.ca/data/en/api/3/action/package_search",),
        access_state="ready",
        full_text_policy="metadata_only",
        license_note="Open Government Licence Canada and record-level metadata; preserve bilingual provenance.",
        policy_url="https://open.canada.ca/en/working-data-api/best-practices",
        refresh_days=7,
        requests_per_second=0.5,
        pilot_budget=250,
        topics=("canada", "government", "public_data", "bilingual", "quebec_context"),
    ),
)


def by_id(source_id: str) -> SourceProfile:
    for profile in BEST_SITES_V1:
        if profile.source_id == source_id:
            return profile
    raise KeyError(source_id)
