"""Omega-PROF-POLY-T package."""

from .absorb_public_research import AbsorptionReport, absorb_public_records, demo_public_research_records
from .action_packet_writer import ActionPacketWriteResult, WrittenActionPacket, render_action_packet, write_action_packets
from .adapter_router import AdapterRoute, RoutedRecords, detect_source_family, route_records
from .artifact_summaries import ArtifactSummary, build_artifact_summary
from .backlog_packet_templates import BacklogPacket, render_backlog_packet
from .changelog_generator import generate_changelog, generate_release_notes
from .claim_graph import ClaimGraph, ClaimNode, build_claim_graph
from .claim_oak_plus import ClaimOAKPlusGraph, ClaimOAKPlusNode, build_claim_oak_plus, expand_claim_oak_plus_node
from .cli import VERSION, run_cli
from .cli_command_groups import CLICommandGroup, CLICommandGroups, build_cli_command_groups, render_cli_command_groups
from .collaboration_markdown import CollaborationMarkdown, render_collaboration_markdown
from .collaboration_recommender import CollaborationPlan, CollaborationRecommendation, recommend_collaborations
from .compact_table_report import render_compact_table, render_portfolio_table, render_ranked_items_table, render_validation_table
from .core import Evidence, OAKDecision, OAKStatus, ProfessorSignal, build_project_forge_prompt, evaluate_signal, rank_signals
from .course_memory_minus import CourseAntiError, CourseMemoryMinus, build_course_memory_minus
from .coursecvcd import CourseCVCDPacket, CourseInput, generate_coursecvcd
from .department_bridge_optimizer import DepartmentBridgeOptimization, OptimizedBridge, optimize_department_bridges
from .department_bridge_report import DepartmentBridgeReport, render_department_bridge_report
from .department_bridge_scoring import DepartmentBridgeScore, score_department_bridge, score_recommendation_bridge
from .department_strategy_matrix import DepartmentStrategyCell, DepartmentStrategyMatrix, build_department_strategy_matrix, render_department_strategy_matrix
from .documentation_index import DocumentationEntry, DocumentationIndex, build_documentation_index, render_documentation_index
from .e2e_pipeline_v09 import EndToEndV09Result, run_v09_e2e_pipeline
from .enriched_graph_exports import professor_graph_to_enriched_graphml
from .evidence_risk_counter import EvidenceRiskCount, count_evidence_risk, render_evidence_risk_count
from .export_bundle import ExportBundleFile, ExportBundleResult, build_export_bundle
from .export_commands import ExportPayloads, build_export_payloads
from .fixture_artifact_generator import FixtureArtifactRun, generate_fixture_artifacts
from .fixture_loader_v08 import combine_fixture_records, demo_combined_fixture_records
from .generated_changelog_plus import generate_changelog_plus
from .generated_report_artifacts import ArtifactManifest, GeneratedArtifact, build_report_artifacts
from .github_packet_generator import GitHubFilePacket, GitHubWorkPacket, generate_github_work_packet, render_github_packet_markdown
from .github_work_bundle import GitHubWorkBundle, build_github_work_bundle, write_github_work_bundle
from .grant_forge import GrantInput, GrantPacket, forge_grant, grant_score
from .graph_exports import professor_graph_to_graphml, professor_graph_to_json
from .ingest_json_pipeline_v2 import IngestJSONPipelineResult, run_ingest_json_pipeline_v2
from .ip_oak_gate import IPGatePacket, IPInput, IPStatus, classify_ip
from .json_exports import packet_digest, to_deterministic_json, to_plain_data
from .lab_oakbench import LabInput, LabOAKBenchPacket, generate_lab_oakbench
from .local_json_loader import LocalJSONLoadResult, load_and_normalize_local_json, load_local_json_records, normalize_local_json_records
from .method_graph import MethodGraph, MethodNode, build_method_graph
from .method_reproduction_packet import MethodReproductionPacket, MethodReproductionSet, build_method_reproduction_packet, build_method_reproduction_set
from .mminus_registry import MMinusEntry, MMinusRegistry, default_mminus_registry, render_mminus_markdown
from .mminus_rules_engine import MMinusDecision, apply_mminus_rules, render_mminus_decision
from .next_actions_engine import NextAction, NextActionPlan, compile_top_next_actions, render_next_actions_markdown
from .oak_ledger_cli import OAKLedgerBundle, build_oak_ledger_bundle, render_oak_ledger_bundle
from .oak_lineage_ledger import OAKLineageEntry, OAKLineageLedger, build_oak_lineage_ledger, render_oak_lineage_ledger
from .oak_packet_manifest import OAKPacketEntry, OAKPacketManifest, build_oak_packet_manifest
from .oak_packet_manifest_plus import OAKPacketManifestPlus, OAKPacketPlusEntry, build_oak_packet_manifest_plus
from .omega_absorb_os_v2 import OmegaAbsorbOSV2, build_omega_absorb_os_v2, render_omega_absorb_os_v2
from .opportunity_ranker import OpportunityRanking, RankedOpportunity, rank_opportunity_bundles, score_bundle
from .package_ci_plan import CIPipelineStep, PackageCIPlan, build_package_ci_plan, render_package_ci_plan
from .package_health import PackageHealthReport, build_package_health_report
from .package_layout_v2 import LayoutSection, PackageLayoutV2, build_package_layout_v2, render_package_layout_v2
from .package_status import PackageStatusReport, build_package_status_report
from .poly_public_adapters import ExpertiseLikeAdapter, PolyPublieLikeAdapter
from .poly_research_twin import PolyResearchTwin, build_poly_research_twin
from .poly_research_twin_v2 import PolyResearchTwinV2, build_poly_research_twin_v2
from .poly_research_twin_v3 import PolyResearchTwinV3, build_poly_research_twin_v3
from .portfolio_optimizer import PortfolioSelection, optimize_portfolio
from .prior_art_packet import PriorArtPacket, generate_prior_art_packet
from .professor_backlog_report import ProfessorBacklogReport, render_all_professor_backlogs, render_professor_backlog
from .professor_genome import ProfessorResearchGenome, build_all_professor_genomes, build_professor_genome
from .professor_graph import HyperEdge, Node, ProfessorGraph, demo_professor_graph
from .professor_graph_integration import research_atoms_to_professor_graph
from .professor_tensor import ProfessorTensor, build_professor_tensor, build_professor_tensors
from .professor_tensor_weights import ProfessorTensorWeights, render_tensor_weights_table, weight_professor_tensor, weight_professor_tensors
from .project_forge import ProjectInput, ProjectPacket, forge_project
from .public_metadata_adapters import GenericPublicMetadataAdapter, PublicMetadataAdapter
from .public_source_registry import PublicSource, PublicSourceRegistry, default_public_source_registry
from .release_bundle import ReleaseBundle, build_release_bundle
from .release_bundle_writer import ReleaseBundleWriteResult, WrittenBundleFile, write_release_bundle
from .release_intelligence import ReleaseIntelligence, build_release_intelligence, render_release_intelligence
from .report_atlas import ReportAtlas, ReportAtlasEntry, build_report_atlas, render_report_atlas
from .report_bundle_contract import ReportBundleContract, build_report_bundle_contract, render_report_bundle_contract
from .report_writer import ReportWriteResult, WrittenReport, default_report_contents, write_reports
from .reports import render_packet_report
from .research_atom import ResearchAtom, atom_from_public_record
from .research_opportunity_compiler import ResearchOpportunityBundle, ResearchOpportunityCompilation, compile_atom_opportunities, compile_research_opportunities
from .roadmap_compiler import RoadmapPlan, RoadmapStep, compile_portfolio_roadmap, render_roadmap_markdown
from .route_confidence_dashboard import RouteConfidenceDashboard, RouteConfidenceRow, build_route_confidence_dashboard, render_route_confidence_dashboard
from .source_oak_policy import SourceOAKPolicy, SourceOAKPolicyReport, apply_source_oak_policy, default_source_oak_policies
from .source_record_validation import RecordValidationFinding, RecordValidationReport, validate_public_records
from .source_registry_schema import SourceSchema, SourceSchemaFinding, SourceSchemaReport, default_source_schemas, validate_records_against_schema
from .source_selection import available_demo_sources, select_demo_records
from .twin_answer_engine import TwinAnswer, answer_twin_question, render_twin_answer
from .version_manifest import VersionEntry, VersionManifest, build_version_manifest
from .workflow_seed import WorkflowSeed, WorkflowSeedStep, build_workflow_seed, render_workflow_seed
from .zero_touch_oak import BlockedActionPacket, GateStatus, OAKCompileResult, compile_oak

__all__ = [name for name in globals() if not name.startswith("_")]
