"""Markdown renderer for local collaboration plans."""

from __future__ import annotations

from dataclasses import dataclass

from .collaboration_recommender import CollaborationPlan
from .department_bridge_scoring import score_recommendation_bridge


@dataclass(frozen=True)
class CollaborationMarkdown:
    markdown: str
    item_count: int
    next_action: str


def render_collaboration_markdown(plan: CollaborationPlan) -> CollaborationMarkdown:
    lines = [
        "# Collaboration Plan",
        "",
        "Generated by Omega absorb v0.8 from public/demo metadata.",
        "",
        "## Recommended pairs",
    ]
    for index, item in enumerate(plan.recommendations, start=1):
        bridge_score = score_recommendation_bridge(item)
        lines.extend(
            [
                f"### {index}. {item.professor_a} x {item.professor_b}",
                f"- base score: {item.score:.4f}",
                f"- bridge score: {bridge_score:.4f}",
                f"- departments: {', '.join(item.complementary_departments) or 'none'}",
                f"- shared keywords: {', '.join(item.shared_keywords) or 'none'}",
                f"- shared methods: {', '.join(item.shared_methods) or 'none'}",
                f"- next action: {item.next_action}",
                "",
            ]
        )
    if not plan.recommendations:
        lines.append("- none yet")
    return CollaborationMarkdown(
        markdown="\n".join(lines).strip() + "\n",
        item_count=len(plan.recommendations),
        next_action="store_collaboration_markdown",
    )
