"""Professor backlog report renderer for Omega absorb Poly professor v0.5."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Tuple

from .opportunity_ranker import OpportunityRanking
from .professor_genome import ProfessorResearchGenome


@dataclass(frozen=True)
class ProfessorBacklogReport:
    professor: str
    markdown: str
    next_action: str


def render_professor_backlog(genome: ProfessorResearchGenome, ranking: OpportunityRanking | None = None) -> ProfessorBacklogReport:
    lines = [
        f"# Professor Backlog - {genome.professor}",
        "",
        "Generated by Omega absorb Poly professor v0.5.",
        "",
        "## Departments",
    ]
    lines.extend(f"- {item}" for item in (genome.departments or ("unknown",)))
    lines.extend(["", "## Expertise keywords"])
    lines.extend(f"- {item}" for item in (genome.expertise_keywords or ("none",)))
    lines.extend(["", "## Course opportunities"])
    lines.extend(f"- {item}" for item in (genome.teaching_opportunities or ("none",)))
    lines.extend(["", "## Project opportunities"])
    lines.extend(f"- {item}" for item in (genome.project_opportunities or ("none",)))
    lines.extend(["", "## Grant opportunities"])
    lines.extend(f"- {item}" for item in (genome.grant_opportunities or ("none",)))
    lines.extend(["", "## IP signals"])
    lines.extend(f"- {item}" for item in (genome.ip_signals or ("none",)))
    lines.extend(["", "## OAK risks"])
    lines.extend(f"- {item}" for item in (genome.oak_risks or ("none",)))
    lines.extend(["", "## Next actions"])
    lines.extend(f"- {item}" for item in genome.next_actions)
    if ranking:
        lines.extend(["", "## Ranked opportunities"])
        for item in ranking.ranked[:10]:
            lines.append(f"- #{item.rank} {item.atom_id} score={item.score:.4f} path={item.recommended_path}")
    return ProfessorBacklogReport(
        professor=genome.professor,
        markdown="\n".join(lines).strip() + "\n",
        next_action="save_markdown_report",
    )


def render_all_professor_backlogs(
    genomes: Iterable[ProfessorResearchGenome],
    ranking: OpportunityRanking | None = None,
) -> Tuple[ProfessorBacklogReport, ...]:
    return tuple(render_professor_backlog(genome, ranking) for genome in genomes)
