"""Markdown report helpers for Omega-PROF-POLY-T."""

from __future__ import annotations

from dataclasses import asdict, is_dataclass
from typing import Any, Iterable


def _value_to_markdown(value: Any) -> str:
    if is_dataclass(value):
        return _dict_to_markdown(asdict(value), level=3)
    if isinstance(value, dict):
        return _dict_to_markdown(value, level=3)
    if isinstance(value, (list, tuple)):
        return "\n".join(f"- {item}" for item in value) or "- none"
    return str(value)


def _dict_to_markdown(data: dict[str, Any], level: int = 2) -> str:
    lines: list[str] = []
    prefix = "#" * level
    for key, value in data.items():
        lines.append(f"{prefix} {key}")
        lines.append(_value_to_markdown(value))
        lines.append("")
    return "\n".join(lines).strip()


def render_packet_report(title: str, packets: Iterable[Any]) -> str:
    lines = [f"# {title}", "", "Generated by Ω-PROF-POLY-T zero-touch report renderer.", ""]
    for index, packet in enumerate(packets, start=1):
        lines.append(f"## Packet {index}: {packet.__class__.__name__}")
        if is_dataclass(packet):
            lines.append(_dict_to_markdown(asdict(packet), level=3))
        else:
            lines.append(str(packet))
        lines.append("")
    return "\n".join(lines).strip() + "\n"
