"""Deterministic source generators for a validated affine-vector kernel."""
from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path

from .ir import affine_vector_ir
from .model import VariantAddress


@dataclass(frozen=True, slots=True)
class GeneratedArtifact:
    language: str
    path: str
    content: str
    sha256: str
    generator_version: str = "omega.polyglot.generator.r02"

    @classmethod
    def from_content(cls, language: str, path: str, content: str) -> "GeneratedArtifact":
        return cls(language, path, content, sha256(content.encode()).hexdigest())


HEADER = "Generated by Ω-POLYGLOT-MULTIVERSE-T∞ R0.2; edit the specification or generator, not this file."


def generate_affine_source(language: str, strategy: str = "scalar") -> GeneratedArtifact:
    affine_vector_ir().validate()
    if language == "python":
        body = f'''# {HEADER}\nfrom __future__ import annotations\n\ndef omega_vector_affine_f64(x, y, scalar):\n    if len(x) != len(y):\n        raise ValueError("x and y must have equal length")\n    return [scalar * xv + yv for xv, yv in zip(x, y, strict=True)]\n'''
        return GeneratedArtifact.from_content(language, "generated/python/vector_affine.py", body)
    if language == "c":
        pragma = "#pragma GCC ivdep\n    " if "simd" in strategy else ""
        body = f'''/* {HEADER} */\n#include <stddef.h>\nint omega_vector_affine_f64(const double *x, const double *y, double scalar, double *out, size_t n) {{\n    if (n && (!x || !y || !out)) return 1;\n    {pragma}for (size_t i = 0; i < n; ++i) out[i] = scalar * x[i] + y[i];\n    return 0;\n}}\n'''
        return GeneratedArtifact.from_content(language, "generated/c/vector_affine.c", body)
    if language == "cpp":
        body = f'''// {HEADER}\n#include <cstddef>\nextern "C" int omega_vector_affine_f64(const double *x, const double *y, double scalar, double *out, std::size_t n) noexcept {{\n    if (n && (!x || !y || !out)) return 1;\n    for (std::size_t i = 0; i < n; ++i) out[i] = scalar * x[i] + y[i];\n    return 0;\n}}\n'''
        return GeneratedArtifact.from_content(language, "generated/cpp/vector_affine.cpp", body)
    if language == "rust":
        body = f'''// {HEADER}\n#[no_mangle]\npub unsafe extern "C" fn omega_vector_affine_f64(x: *const f64, y: *const f64, scalar: f64, out: *mut f64, n: usize) -> i32 {{\n    if n > 0 && (x.is_null() || y.is_null() || out.is_null()) {{ return 1; }}\n    let xs = std::slice::from_raw_parts(x, n);\n    let ys = std::slice::from_raw_parts(y, n);\n    let output = std::slice::from_raw_parts_mut(out, n);\n    for i in 0..n {{ output[i] = scalar * xs[i] + ys[i]; }}\n    0\n}}\n'''
        return GeneratedArtifact.from_content(language, "generated/rust/src/lib.rs", body)
    raise ValueError(f"unsupported language: {language}")


def generate_variant(variant: VariantAddress) -> GeneratedArtifact:
    if variant.algorithm_id.split(".")[1] != "affine":
        raise NotImplementedError("R0.2 executable generation is certified only for affine kernels")
    return generate_affine_source(variant.language, variant.strategy)


def write_artifact(root: Path, artifact: GeneratedArtifact) -> Path:
    destination = root / artifact.path
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(artifact.content, encoding="utf-8")
    return destination
