"""Ω-ST — Sciences de Tristan executable core."""

from .ait_oak import AITOAK, OAKReview
from .bayes_tristan_engine import BayesTristanEngine
from .hyper_best import (
    BenchmarkArena,
    BenchmarkArenaForge,
    ImpactRoute,
    ImpactRouter,
    PaperForge,
    PaperSeed,
    PrototypeContract,
    PrototypeForge,
    TheoryReactor,
    autonomous_research_loop,
)
from .science_card import BayesTristanVector, OAKStatus, ScienceCard, cards_from_mappings
from .v2_extensions import (
    CanonScore,
    ClaimTransmutation,
    ClaimTransmuter,
    MemoryMinusEngine,
    MemoryMinusRule,
    OAKCourt,
    OAKCourtReview,
    OAKDecision,
    PromotionGateResult,
    PromotionGates,
    Residue,
    ResidueMiner,
    ScienceOrganism,
    portfolio_dashboard,
)

__all__ = [
    "AITOAK",
    "OAKReview",
    "BayesTristanEngine",
    "BayesTristanVector",
    "OAKStatus",
    "ScienceCard",
    "cards_from_mappings",
    "CanonScore",
    "ClaimTransmutation",
    "ClaimTransmuter",
    "MemoryMinusEngine",
    "MemoryMinusRule",
    "OAKCourt",
    "OAKCourtReview",
    "OAKDecision",
    "PromotionGateResult",
    "PromotionGates",
    "Residue",
    "ResidueMiner",
    "ScienceOrganism",
    "portfolio_dashboard",
    "BenchmarkArena",
    "BenchmarkArenaForge",
    "ImpactRoute",
    "ImpactRouter",
    "PaperForge",
    "PaperSeed",
    "PrototypeContract",
    "PrototypeForge",
    "TheoryReactor",
    "autonomous_research_loop",
]
